#!/usr/bin/env bash
set -euo pipefail

MIMO_CODE_DIR="${MIMO_CODE_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"
REPO_ROOT="${REPO_ROOT:-$(cd "$MIMO_CODE_DIR/../../../../../.." && pwd)}"
FUSION_ROUTER_DIR="${FUSION_ROUTER_DIR:-$(cd "$REPO_ROOT/.." && pwd)/sii-fusion-router}"
MIMO_ROUTER_WHEEL_MOUNT_PATH="${MIMO_ROUTER_WHEEL_MOUNT_PATH:-/opt/sii-fusion-router/router.whl}"
MIMO_ROUTER_CONFIG_MOUNT_PATH="${MIMO_ROUTER_CONFIG_MOUNT_PATH:-/opt/sii-fusion-router/router-config.json}"
MIMO_ROUTER_PIPELINE="${MIMO_ROUTER_PIPELINE:-mimo_max}"
MIMO_ROUTER_ARTIFACT_ROOT="${MIMO_ROUTER_ARTIFACT_ROOT:-/logs/agent/router}"
MIMO_ROUTER_SUMMARY_PATH="${MIMO_ROUTER_SUMMARY_PATH:-/logs/agent/router-run-summary.json}"

export MIMO_CODE_DIR REPO_ROOT FUSION_ROUTER_DIR
export MIMO_ROUTER_WHEEL MIMO_ROUTER_VERSION MIMO_ROUTER_CONFIG
export MIMO_ROUTER_WHEEL_MOUNT_PATH MIMO_ROUTER_CONFIG_MOUNT_PATH
export MIMO_ROUTER_PIPELINE MIMO_ROUTER_ARTIFACT_ROOT MIMO_ROUTER_SUMMARY_PATH
