#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../../.." && pwd)"

# Load shared site configuration with the same precedence used by the top-level
# CLI and DinD entry point: runtime/exported values, config.local.env,
# config.env, then the defaults below.
# shellcheck source=../../../../scripts/config_loader.sh
source "$REPO_ROOT/scripts/config_loader.sh"
agent_fleet_load_config "$REPO_ROOT"
# shellcheck source=opensandbox_s3_profile.sh
source "$SCRIPT_DIR/opensandbox_s3_profile.sh"

# Keep setup-managed and explicitly supplied prerequisite directories visible
# for direct Harbor entry points as well as scripts/run_fleet.sh.
# shellcheck source=../../../../scripts/prerequisites.sh
source "$REPO_ROOT/scripts/prerequisites.sh"
agent_fleet_prerequisite_init_path
agent_fleet_prerequisite_init_runtime

AGENTS_DIR="${AGENTS_DIR:-$REPO_ROOT/Agents}"
TASKS_DIR="${TASKS_DIR:-$REPO_ROOT/Tasks}"
HARBOR_CLAUDE_CODE_DIR="${HARBOR_CLAUDE_CODE_DIR:-$AGENTS_DIR/Harbor-claude-code}"
HARBOR_OPENCODE_DIR="${HARBOR_OPENCODE_DIR:-$AGENTS_DIR/Harbor-opencode}"
HARBOR_PI_DIR="${HARBOR_PI_DIR:-$AGENTS_DIR/Harbor-pi}"
WORKSPACE_DIR="${WORKSPACE_DIR:-/workspace}"

RUN_ID="${RUN_ID:-$(date +%Y-%m-%d-%H%M)-harbor-tui}"
TOTAL_WORKERS="${TOTAL_WORKERS:-10}"
N_ATTEMPTS="${N_ATTEMPTS:-1}"
MAX_RETRIES="${MAX_RETRIES:-${HARBOR_MAX_RETRIES:-2}}"
# AGENT selects the runner: claude-code (default), opencode, or pi.
AGENT="${AGENT:-claude-code}"
MODEL="${MODEL:-minimax2.7}"
_HARBOR_EFFECTIVE_MODEL="${HARBOR_MODEL:-$MODEL}"
# OpenCode requires provider/model for custom providers. Keep MODEL shared with
# claude-code, and only add this prefix when AGENT=opencode.
OPENCODE_PROVIDER="${OPENCODE_PROVIDER:-custom}"
PI_PROVIDER="${PI_PROVIDER:-}"

HARBOR_ROOT="${HARBOR_ROOT:-/workspace/harbor}"
# Dataset selection:
#   DATASET_NAME: auto, seta, smith, terminalbench21, sweverify,
#     or a Harbor registry dataset id such as owner/name or owner/name@version.
#     seta, terminalbench21, and sweverify are registry aliases. smith is local.
#     For a local/offline checkout, use auto so the dataset is inferred from
#     DATASET_PATH.
#   DATASET_PATH examples:
#     /workspace/seta-env/Harbor-Dataset
#     /workspace/harbor/datasets/swesmith
#     /workspace/terminal-bench-2-1/tasks
#     /workspace/swebench-verified
# TASK_SOURCE_FILE can override the built-in task list under Tasks/.
DATASET_NAME="${DATASET_NAME:-auto}"
DATASET_PATH="${DATASET_PATH:-/workspace/seta-env/Harbor-Dataset}"
METRIC_MODE="${METRIC_MODE:-auto}"
HARBOR_TERMINALBENCH21_REGISTRY_ID="terminal-bench/terminal-bench-2-1"

# Host-direct runs must not assume that the caller can write to /workspace.
# The checkout-local runs directory is ignored by git, mounted at the same path
# by dind-run.sh, and remains overrideable for managed deployments.
OUTPUT_ROOT="${OUTPUT_ROOT:-$REPO_ROOT/runs}"
OUTPUT_PATH="${OUTPUT_PATH:-${OUTPUT_ROOT}/${RUN_ID}}"
TASK_SOURCE_FILE="${TASK_SOURCE_FILE:-}"
TASK_FILE="${TASK_FILE:-${OUTPUT_PATH}/tasks.txt}"
FLEET_TASKS="${FLEET_TASKS:-}"
# Per-agent state so toggling AGENT between runs in the same OUTPUT_PATH
# cannot cross-contaminate queue/wheel/image state. TASK_FILE stays shared.
QUEUE_DIR="${QUEUE_DIR:-${OUTPUT_PATH}/queue/${AGENT}}"
RUNTIME_DIR="${RUNTIME_DIR:-${OUTPUT_PATH}/runtime/${AGENT}}"
LAYOUT_FILE="${LAYOUT_FILE:-${OUTPUT_PATH}/harbor-layout.kdl}"
JOBS_ROOT="${JOBS_ROOT:-${OUTPUT_PATH}/jobs/${AGENT}}"
HARBOR_ONLINE_ANALYSIS="${HARBOR_ONLINE_ANALYSIS:-0}"
HARBOR_ONLINE_ANALYSIS_POLL_INTERVAL="${HARBOR_ONLINE_ANALYSIS_POLL_INTERVAL:-1}"
HARBOR_ONLINE_ANALYSIS_DIR="${HARBOR_ONLINE_ANALYSIS_DIR:-${OUTPUT_PATH}/online-analysis}"
HARBOR_ONLINE_ANALYSIS_PID_FILE="${HARBOR_ONLINE_ANALYSIS_PID_FILE:-${RUNTIME_DIR}/online-rule-analyzer.pid}"
HARBOR_ONLINE_ANALYSIS_LOG_FILE="${HARBOR_ONLINE_ANALYSIS_LOG_FILE:-${RUNTIME_DIR}/online-rule-analyzer.log}"
HARBOR_EARLY_STOP="${HARBOR_EARLY_STOP:-0}"
HARBOR_ZELLIJ_CLOSE_ON_COMPLETE="${HARBOR_ZELLIJ_CLOSE_ON_COMPLETE:-1}"
HARBOR_ZELLIJ_KEEP_ON_FAILURE="${HARBOR_ZELLIJ_KEEP_ON_FAILURE:-}"
HARBOR_MONITOR_ENABLED="${HARBOR_MONITOR_ENABLED:-1}"
HARBOR_MONITOR_DIR="${HARBOR_MONITOR_DIR:-${OUTPUT_PATH}/monitor}"
HARBOR_MONITOR_PID_FILE="${HARBOR_MONITOR_PID_FILE:-${RUNTIME_DIR}/harbor-monitor.pid}"
HARBOR_MONITOR_LOG_FILE="${HARBOR_MONITOR_LOG_FILE:-${RUNTIME_DIR}/harbor-monitor.log}"
HARBOR_BENCHMARK_PID_FILE="${HARBOR_BENCHMARK_PID_FILE:-${RUNTIME_DIR}/harbor-benchmark.pid}"
HARBOR_BENCHMARK_EXIT_FILE="${HARBOR_BENCHMARK_EXIT_FILE:-${RUNTIME_DIR}/harbor-benchmark.exit}"
HARBOR_JOB_DIR_FILE="${HARBOR_JOB_DIR_FILE:-${RUNTIME_DIR}/harbor-job-dir}"
HARBOR_MONITOR_RESTART_CMD="${HARBOR_MONITOR_RESTART_CMD:-}"
HARBOR_MONITOR_STOP_CMD="${HARBOR_MONITOR_STOP_CMD:-}"
HARBOR_MONITOR_INTERVAL="${HARBOR_MONITOR_INTERVAL:-30}"
HARBOR_MONITOR_STARTUP_GRACE="${HARBOR_MONITOR_STARTUP_GRACE:-300}"
HARBOR_MONITOR_STALL_SECONDS="${HARBOR_MONITOR_STALL_SECONDS:-1800}"
HARBOR_MONITOR_MAX_RETRIES="${HARBOR_MONITOR_MAX_RETRIES:-3}"
HARBOR_MONITOR_CONFIGURED_TIMEOUT="${HARBOR_MONITOR_CONFIGURED_TIMEOUT:-}"

API_KEY="${API_KEY:-xxx}"
BASE_URL="${BASE_URL:-}"
# Normalize to a versionless API root: callers may supply a value already ending
# in /v1, but the endpoints below append /v1 (or /v1/chat/completions), so strip
# one trailing /v1 to avoid doubling it.
if [[ -n "$BASE_URL" ]]; then
  BASE_URL="${BASE_URL%/}"
  BASE_URL="${BASE_URL%/v1}"
fi
HARBOR_ANTHROPIC_BASE_URL="${HARBOR_ANTHROPIC_BASE_URL:-${ANTHROPIC_BASE_URL:-${BASE_URL%/}}}"
HARBOR_ANTHROPIC_BASE_URL="${HARBOR_ANTHROPIC_BASE_URL%/}"
HARBOR_ANTHROPIC_BASE_URL="${HARBOR_ANTHROPIC_BASE_URL%/v1}"
HARBOR_ANTHROPIC_AUTH_TOKEN="${HARBOR_ANTHROPIC_AUTH_TOKEN:-${ANTHROPIC_AUTH_TOKEN:-$API_KEY}}"
HARBOR_ANALYZER_API_KEY="${HARBOR_ANALYZER_API_KEY:-$HARBOR_ANTHROPIC_AUTH_TOKEN}"
HARBOR_ANALYZER_BASE_URL="${HARBOR_ANALYZER_BASE_URL:-${HARBOR_ANTHROPIC_BASE_URL:+${HARBOR_ANTHROPIC_BASE_URL}/v1}}"
HARBOR_ANALYZER_MODEL="${HARBOR_ANALYZER_MODEL:-$_HARBOR_EFFECTIVE_MODEL}"
HARBOR_ANALYZER_PI_PROVIDER="${HARBOR_ANALYZER_PI_PROVIDER:-harbor-analyzer}"
HARBOR_ANALYZER_NO_PROXY="${HARBOR_ANALYZER_NO_PROXY:-0}"
HARBOR_ANALYZER_ENABLED="${HARBOR_ANALYZER_ENABLED:-$HARBOR_MONITOR_ENABLED}"
HARBOR_ANALYZER_MODE="${HARBOR_ANALYZER_MODE:-handover-follow}"
HARBOR_ANALYZER_OUTPUT_DIR="${HARBOR_ANALYZER_OUTPUT_DIR:-${OUTPUT_PATH}/analyzer}"
HARBOR_ANALYZER_PID_FILE="${HARBOR_ANALYZER_PID_FILE:-${RUNTIME_DIR}/harbor-analyzer.pid}"
HARBOR_ANALYZER_SUPERVISOR_PID_FILE="${HARBOR_ANALYZER_SUPERVISOR_PID_FILE:-${RUNTIME_DIR}/harbor-analyzer-supervisor.pid}"
HARBOR_ANALYZER_SUPERVISOR_ID_FILE="${HARBOR_ANALYZER_SUPERVISOR_ID_FILE:-${RUNTIME_DIR}/harbor-analyzer-supervisor.identity}"
HARBOR_ANALYZER_LOG_FILE="${HARBOR_ANALYZER_LOG_FILE:-${RUNTIME_DIR}/harbor-analyzer.log}"
HARBOR_ANALYZER_POLL_INTERVAL="${HARBOR_ANALYZER_POLL_INTERVAL:-5}"
HARBOR_ANALYZER_TIMEOUT="${HARBOR_ANALYZER_TIMEOUT:-900}"
HARBOR_ANALYZER_MAX_CONCURRENCY="${HARBOR_ANALYZER_MAX_CONCURRENCY:-1}"
HARBOR_FIXER_API_KEY="${HARBOR_FIXER_API_KEY:-$HARBOR_ANTHROPIC_AUTH_TOKEN}"
HARBOR_FIXER_BASE_URL="${HARBOR_FIXER_BASE_URL:-${HARBOR_ANTHROPIC_BASE_URL:+${HARBOR_ANTHROPIC_BASE_URL}/v1}}"
HARBOR_FIXER_MODEL="${HARBOR_FIXER_MODEL:-$_HARBOR_EFFECTIVE_MODEL}"
HARBOR_FIXER_PI_BIN="${HARBOR_FIXER_PI_BIN:-pi}"
HARBOR_FIXER_PI_PROVIDER="${HARBOR_FIXER_PI_PROVIDER:-harbor-fixer}"
HARBOR_FIXER_NO_PROXY="${HARBOR_FIXER_NO_PROXY:-0}"
HARBOR_FIXER_AGENT_TIMEOUT="${HARBOR_FIXER_AGENT_TIMEOUT:-900}"
HARBOR_FIXER_EXECUTION_TIMEOUT="${HARBOR_FIXER_EXECUTION_TIMEOUT:-300}"
HARBOR_FIXER_SUMMARY_LIMIT="${HARBOR_FIXER_SUMMARY_LIMIT:-4000}"
HARBOR_FIXER_MAX_CONCURRENCY="${HARBOR_FIXER_MAX_CONCURRENCY:-4}"
HARBOR_FIXER_MAX_TASK_SUMMARY_CHARS="${HARBOR_FIXER_MAX_TASK_SUMMARY_CHARS:-24000}"
HARBOR_FIXER_MAX_TASK_SUMMARIES_CHARS="${HARBOR_FIXER_MAX_TASK_SUMMARIES_CHARS:-400000}"
OPIK_URL="${OPIK_URL:-}"
# OPIK_URL is the operator switch for running with or without Opik. The shared
# gate also honors OPIK_TRACK_DISABLE as a runtime safety override.
harbor_trace_to_opik_enabled() {
  OPIK_URL="${OPIK_URL:-}" OPIK_TRACK_DISABLE="${OPIK_TRACK_DISABLE:-}" \
    python3 "$SCRIPT_DIR/opik_trace_gate.py"
}
OPIK_URL_OVERRIDE="${OPIK_URL_OVERRIDE:-$OPIK_URL}"
OPIK_BASE="${OPIK_BASE:-${OPIK_URL_OVERRIDE%/api}}"

harbor_run_name_component() {
  local value
  value="$(printf '%s' "$1" |
    LC_ALL=C tr -cs 'A-Za-z0-9_-' '-' |
    sed 's/^-*//; s/-*$//' |
    cut -c1-"${2:-32}")"
  value="${value#-}"
  value="${value%-}"
  printf '%s\n' "${value:-run}"
}

HARBOR_RUN_TIMESTAMP="${HARBOR_RUN_TIMESTAMP:-$(date +%Y%m%d-%H%M%S)}"
HARBOR_SESSION_TIMESTAMP="${HARBOR_SESSION_TIMESTAMP:-$(date +%H%M%S)}"
HARBOR_RUN_AGENT_NAME="$(harbor_run_name_component "$AGENT" 20)"
HARBOR_RUN_DATASET_NAME="$(harbor_run_name_component "$DATASET_NAME" 32)"
HARBOR_RUN_MODEL_NAME="$(harbor_run_name_component "$_HARBOR_EFFECTIVE_MODEL" 32)"
# Both defaults describe the effective run. Keep the Zellij name independent
# from a caller-supplied Opik project so an unrelated project cannot relabel or
# collide with the local session.
OPIK_PROJECT_NAME="${OPIK_PROJECT_NAME:-agent-fleet-${HARBOR_RUN_AGENT_NAME}-${HARBOR_RUN_DATASET_NAME}-${HARBOR_RUN_MODEL_NAME}-${HARBOR_RUN_TIMESTAMP}}"
HARBOR_ZELLIJ_SESSION_NAME="${HARBOR_ZELLIJ_SESSION_NAME:-$(harbor_run_name_component "h-${HARBOR_SESSION_TIMESTAMP}-$$-$(harbor_run_name_component "$AGENT" 8)-$(harbor_run_name_component "$DATASET_NAME" 8)-$(harbor_run_name_component "$_HARBOR_EFFECTIVE_MODEL" 8)" 40)}"
# Some launch wrappers pass the placeholder literally. Do not forward that
# into task containers, otherwise Opik auth/config becomes invalid.
if [[ "${OPIK_API_KEY:-}" == '${OPIK_API_KEY}' ]]; then
  unset OPIK_API_KEY
fi
OPIK_API_KEY="${OPIK_API_KEY:-local-dev-key}"
OPIK_WORKSPACE="${OPIK_WORKSPACE:-default}"
CC_OPIK_DEBUG="${CC_OPIK_DEBUG:-true}"

CLAUDE_CODE_VERSION="${CLAUDE_CODE_VERSION:-2.1.90}"
CLAUDE_CODE_TGZ_BASENAME="${CLAUDE_CODE_TGZ_BASENAME:-claude-code-${CLAUDE_CODE_VERSION}.tgz}"
PI_VERSION="${PI_VERSION:-0.81.1}"
PI_TGZ_BASENAME="${PI_TGZ_BASENAME:-pi-coding-agent-${PI_VERSION}.tgz}"
PI_NODE_RUNTIME_BASENAME="${PI_NODE_RUNTIME_BASENAME:-pi-node-runtime.tar.gz}"
PI_RUNTIME_BASENAME="${PI_RUNTIME_BASENAME:-pi-runtime-${PI_VERSION}.tar.gz}"
PI_THINKING_LEVEL="${PI_THINKING_LEVEL:-high}"
LOCAL_WHEEL_DIR="${LOCAL_WHEEL_DIR:-$AGENT_FLEET_CACHE_DIR/harbor-deps}"
LOCAL_WHEEL_PORT="${LOCAL_WHEEL_PORT:-18765}"
LOCAL_WHEEL_PORT_ATTEMPTS="${LOCAL_WHEEL_PORT_ATTEMPTS:-3}"
LOCAL_WHEEL_HOST_IP="${LOCAL_WHEEL_HOST_IP:-}"
if [[ -z "${LOCAL_WHEEL_HOST_IP:-}" ]] && command -v ip >/dev/null 2>&1; then
  LOCAL_WHEEL_HOST_IP="$(ip -4 addr show docker0 2>/dev/null | awk '/inet /{print $2}' | cut -d/ -f1 | head -n 1 || true)"
fi
if [[ -z "${LOCAL_WHEEL_HOST_IP:-}" ]] && command -v ip >/dev/null 2>&1; then
  LOCAL_WHEEL_HOST_IP="$(ip route 2>/dev/null | awk '/^default /{print $3; exit}' || true)"
fi
if [[ -z "${HARBOR_LOCAL_WHEEL_SERVER_URL:-}" && -n "${LOCAL_WHEEL_HOST_IP:-}" ]]; then
  HARBOR_LOCAL_WHEEL_SERVER_URL="http://${LOCAL_WHEEL_HOST_IP}:${LOCAL_WHEEL_PORT}"
fi
if [[ -z "${HARBOR_LOCAL_CLAUDE_TGZ_URL:-}" && -n "${HARBOR_LOCAL_WHEEL_SERVER_URL:-}" ]]; then
  HARBOR_LOCAL_CLAUDE_TGZ_URL="${HARBOR_LOCAL_WHEEL_SERVER_URL%/}/${CLAUDE_CODE_TGZ_BASENAME}"
fi
HARBOR_REMOTE_WHEEL_SERVER_URLS="${HARBOR_REMOTE_WHEEL_SERVER_URLS:-}"
EFFECTIVE_WHEEL_URL_FILE="${RUNTIME_DIR}/effective-wheel-url"
EFFECTIVE_CLAUDE_TGZ_URL_FILE="${RUNTIME_DIR}/effective-claude-tgz-url"
LOCAL_DEPS_LOG_FILE="${RUNTIME_DIR}/local-deps-prepare.log"
# Retain the original switch and status paths for compatibility. The runner is
# image-owned in DinD and setup-owned on a direct host; workloads only validate.
HARBOR_RUNNER_PREPARE="${HARBOR_RUNNER_PREPARE:-1}"
HARBOR_RUNNER_IMAGE_DIR="${HARBOR_RUNNER_IMAGE_DIR:-/opt/harbor-runner}"
HARBOR_RUNNER_HOST_DIR="${HARBOR_RUNNER_HOST_DIR:-$HOME/.local/share/agent-fleet/harbor-runner}"
if [[ -z "${HARBOR_RUNNER_DIR:-}" ]]; then
  if [[ -d "$HARBOR_RUNNER_IMAGE_DIR" ]]; then
    HARBOR_RUNNER_DIR="$HARBOR_RUNNER_IMAGE_DIR"
  else
    HARBOR_RUNNER_DIR="$HARBOR_RUNNER_HOST_DIR"
  fi
fi
if [[ -n "${HARBOR_RUNNER_PYTHON_VERSION:-}" &&
      -n "${HARBOR_RUNNER_PYTHON:-}" &&
      "$HARBOR_RUNNER_PYTHON_VERSION" != "$HARBOR_RUNNER_PYTHON" ]]; then
  echo "HARBOR_RUNNER_PYTHON_VERSION and legacy HARBOR_RUNNER_PYTHON disagree" >&2
  exit 1
fi
HARBOR_RUNNER_PYTHON_VERSION="${HARBOR_RUNNER_PYTHON_VERSION:-${HARBOR_RUNNER_PYTHON:-}}"
HARBOR_RUNNER_PYTHON_VERSION_FILE="$HARBOR_RUNNER_DIR/.agent-fleet-python-version"
if [[ -z "$HARBOR_RUNNER_PYTHON_VERSION" &&
      "$HARBOR_RUNNER_DIR" == "$HARBOR_RUNNER_HOST_DIR" &&
      -f "$HARBOR_RUNNER_PYTHON_VERSION_FILE" ]]; then
  IFS= read -r HARBOR_RUNNER_PYTHON_VERSION < "$HARBOR_RUNNER_PYTHON_VERSION_FILE"
fi
HARBOR_RUNNER_PYTHON_VERSION="${HARBOR_RUNNER_PYTHON_VERSION:-3.12.13}"
HARBOR_OPIK_BIN="${HARBOR_OPIK_BIN:-$HARBOR_RUNNER_DIR/bin/opik}"
HARBOR_CLI_BIN="${HARBOR_CLI_BIN:-$HARBOR_RUNNER_DIR/bin/harbor}"
HARBOR_OPIK_PYTHON="${HARBOR_OPIK_PYTHON:-$HARBOR_RUNNER_DIR/bin/python}"
HARBOR_RUNNER_REQUIREMENTS="${HARBOR_RUNNER_REQUIREMENTS:-$SCRIPT_DIR/runner-requirements.txt}"
HARBOR_RUNNER_PREPARE_STATUS_FILE="${RUNTIME_DIR}/harbor-runner-prepare.status"
HARBOR_RUNNER_PREPARE_LOG_FILE="${RUNTIME_DIR}/harbor-runner-prepare.log"

# Harbor CLI defaults. Keep adapter-specific values here so harboropik.sh and
# the zellij worker scripts cannot drift into different model/network settings.
HARBOR_LIMIT="${HARBOR_LIMIT:-}"
HARBOR_RUNS="${HARBOR_RUNS:-$N_ATTEMPTS}"
HARBOR_AGENT_IMPORT_PATH="${HARBOR_AGENT_IMPORT_PATH:-}"
HARBOR_MODEL="${HARBOR_MODEL:-$_HARBOR_EFFECTIVE_MODEL}"
if [[ "$AGENT" == "pi" && -z "$HARBOR_AGENT_IMPORT_PATH" ]]; then
  HARBOR_AGENT_IMPORT_PATH="pi_harbor:AgentFleetPi"
fi
if [[ "$AGENT" == "pi" && -z "$PI_PROVIDER" && -n "$HARBOR_ANTHROPIC_BASE_URL" ]]; then
  # Keep the Pi provider name tied to the gateway host. env.py uses the same
  # derivation while rendering models.json, so the CLI model and config agree.
  PI_PROVIDER="$(python3 - "$HARBOR_ANTHROPIC_BASE_URL" <<'PY'
from urllib.parse import urlparse
import sys

print((urlparse(sys.argv[1]).hostname or "").lower())
PY
)"
fi
if [[ "$AGENT" == "opencode" && "$HARBOR_MODEL" != */* && -n "$OPENCODE_PROVIDER" ]]; then
  HARBOR_MODEL="${OPENCODE_PROVIDER}/${HARBOR_MODEL}"
fi
if [[ "$AGENT" == "pi" && "$HARBOR_MODEL" != */* && -n "$PI_PROVIDER" ]]; then
  HARBOR_MODEL="${PI_PROVIDER}/${HARBOR_MODEL}"
fi
INCLUDE_TASKS="${INCLUDE_TASKS:-${HARBOR_INCLUDE_TASKS:-}}"
HARBOR_DRY_RUN="${HARBOR_DRY_RUN:-0}"
MIN_TEST="${MIN_TEST:-0}"
MIN_TEST_INCLUDE_TASK="${MIN_TEST_INCLUDE_TASK:-fix-git}"
HARBOR_N_CONCURRENT="${HARBOR_N_CONCURRENT:-$TOTAL_WORKERS}"
HARBOR_MAX_RETRIES="${HARBOR_MAX_RETRIES:-$MAX_RETRIES}"
HARBOR_RETRY_INCLUDE_EXCEPTIONS="${HARBOR_RETRY_INCLUDE_EXCEPTIONS-}"
HARBOR_RETRY_EXCLUDE_EXCEPTIONS="${HARBOR_RETRY_EXCLUDE_EXCEPTIONS-RewardFileNotFoundError,RewardFileEmptyError,VerifierOutputParseError}"
HARBOR_AK_MAX_TURNS="${HARBOR_AK_MAX_TURNS:-}"
HARBOR_AK_COLLECT_ROLLOUT_DETAILS="${HARBOR_AK_COLLECT_ROLLOUT_DETAILS:-}"
HARBOR_AK_ENABLE_SUMMARIZE="${HARBOR_AK_ENABLE_SUMMARIZE:-}"
HARBOR_DISALLOWED_TOOLS="${HARBOR_DISALLOWED_TOOLS:-WebSearch WebFetch RemoteTrigger AskUserQuestion}"
HARBOR_APPEND_SYSTEM_PROMPT="${HARBOR_APPEND_SYSTEM_PROMPT:-Use English only for all reasoning, messages, filenames, and tool arguments. Use ASCII characters only unless reading existing non-ASCII file contents is strictly necessary.}"
HARBOR_API_BASE="${HARBOR_API_BASE:-${HARBOR_ANTHROPIC_BASE_URL%/}/v1/chat/completions}"
ROLLOUT="${ROLLOUT:-0}"
HARBOR_TEMPERATURE="${HARBOR_TEMPERATURE:-}"
HARBOR_TOP_P="${HARBOR_TOP_P:-}"
HARBOR_MAX_TOKENS="${HARBOR_MAX_TOKENS:-}"
if [[ "$ROLLOUT" == "1" ]]; then
  HARBOR_TEMPERATURE=""
  HARBOR_TOP_P=""
  HARBOR_MAX_TOKENS=""
fi
PI_MODELS_CONFIG="${PI_MODELS_CONFIG:-}"
PI_SETTINGS_CONFIG="${PI_SETTINGS_CONFIG:-}"
PI_SUPPORTS_REASONING_EFFORT="${PI_SUPPORTS_REASONING_EFFORT:-}"
PI_THINKING_LEVEL_MAP="${PI_THINKING_LEVEL_MAP:-}"
PI_EXTENSION_SOURCE="${PI_EXTENSION_SOURCE:-$AGENTS_DIR/Harbor-pi/extensions}"
PI_EXTENSION_DIR="${PI_EXTENSION_DIR:-/opt/tb-pi/extensions}"
if [[ "$AGENT" == "pi" ]]; then
  if [[ -z "$PI_MODELS_CONFIG" ]]; then
    PI_MODELS_CONFIG="$(
      PI_PROVIDER="$PI_PROVIDER" \
      HARBOR_MODEL="$HARBOR_MODEL" \
      HARBOR_ANTHROPIC_BASE_URL="$HARBOR_ANTHROPIC_BASE_URL" \
      HARBOR_MAX_TOKENS="$HARBOR_MAX_TOKENS" \
      PI_SUPPORTS_REASONING_EFFORT="$PI_SUPPORTS_REASONING_EFFORT" \
      PI_THINKING_LEVEL_MAP="$PI_THINKING_LEVEL_MAP" \
        python3 "$SCRIPT_DIR/env.py" pi-models-config
    )"
  fi
  if [[ -z "$PI_SETTINGS_CONFIG" ]]; then
    PI_SETTINGS_CONFIG="$(
      PI_PROVIDER="$PI_PROVIDER" \
      HARBOR_MODEL="$HARBOR_MODEL" \
      PI_THINKING_LEVEL="$PI_THINKING_LEVEL" \
        python3 "$SCRIPT_DIR/env.py" pi-settings-config
    )"
  fi
fi
if [[ -z "${HARBOR_LLM_KWARGS:-}" ]]; then
  HARBOR_LLM_KWARGS="$(
    HARBOR_ANTHROPIC_AUTH_TOKEN="$HARBOR_ANTHROPIC_AUTH_TOKEN" \
    HARBOR_TEMPERATURE="$HARBOR_TEMPERATURE" \
    HARBOR_TOP_P="$HARBOR_TOP_P" \
      python3 "$SCRIPT_DIR/env.py" llm-kwargs
  )"
fi
_HARBOR_OUTPUT_TOKEN_LIMIT="${HARBOR_MAX_TOKENS:-65536}"
HARBOR_MAX_NEW_TOKENS="${HARBOR_MAX_NEW_TOKENS:-$_HARBOR_OUTPUT_TOKEN_LIMIT}"
HARBOR_MODEL_INFO="${HARBOR_MODEL_INFO:-}"
if [[ -z "$HARBOR_MODEL_INFO" ]]; then
  HARBOR_MODEL_INFO="$(
    _HARBOR_OUTPUT_TOKEN_LIMIT="$_HARBOR_OUTPUT_TOKEN_LIMIT" \
      python3 "$SCRIPT_DIR/env.py" model-info
  )"
fi
HARBOR_ANTHROPIC_CUSTOM_HEADERS="${HARBOR_ANTHROPIC_CUSTOM_HEADERS:-${ANTHROPIC_CUSTOM_HEADERS:-}}"
HARBOR_CLAUDE_CODE_MAX_OUTPUT_TOKENS="${HARBOR_CLAUDE_CODE_MAX_OUTPUT_TOKENS:-$_HARBOR_OUTPUT_TOKEN_LIMIT}"
HARBOR_CLAUDE_CODE_DISABLE_AUTOUPDATER="${HARBOR_CLAUDE_CODE_DISABLE_AUTOUPDATER:-1}"

# Advanced Claude Code model routing defaults follow Harbor's effective task
# model. This keeps direct HARBOR_MODEL compatibility scoped to Harbor without
# promoting it into the repository-wide MODEL variable.
HARBOR_ANTHROPIC_MODEL="${HARBOR_ANTHROPIC_MODEL:-$HARBOR_MODEL}"
HARBOR_ANTHROPIC_DEFAULT_OPUS_MODEL="${HARBOR_ANTHROPIC_DEFAULT_OPUS_MODEL:-$HARBOR_MODEL}"
HARBOR_ANTHROPIC_DEFAULT_SONNET_MODEL="${HARBOR_ANTHROPIC_DEFAULT_SONNET_MODEL:-$HARBOR_MODEL}"
HARBOR_ANTHROPIC_DEFAULT_HAIKU_MODEL="${HARBOR_ANTHROPIC_DEFAULT_HAIKU_MODEL:-$HARBOR_MODEL}"
HARBOR_CLAUDE_CODE_SUBAGENT_MODEL="${HARBOR_CLAUDE_CODE_SUBAGENT_MODEL:-$HARBOR_MODEL}"
HARBOR_CLAUDE_CODE_EFFORT_LEVEL="${HARBOR_CLAUDE_CODE_EFFORT_LEVEL:-max}"

HARBOR_TIMEOUT_MULTIPLIER="${HARBOR_TIMEOUT_MULTIPLIER:-3.0}"
# Overrides only the agent execution timeout. Leave empty to use HARBOR_TIMEOUT_MULTIPLIER.
HARBOR_AGENT_TIMEOUT_MULTIPLIER="${HARBOR_AGENT_TIMEOUT_MULTIPLIER:-}"
HARBOR_AGENT_SETUP_TIMEOUT_MULTIPLIER="${HARBOR_AGENT_SETUP_TIMEOUT_MULTIPLIER:-20}"
# Set to 1 only when Harbor prebuilt task images fail to pull from registry mirrors;
# this bypasses prebuilt pulls and builds from each task's local Dockerfile instead.
HARBOR_FORCE_BUILD="${HARBOR_FORCE_BUILD:-0}"
HARBOR_DEBUG="${HARBOR_DEBUG:-0}"
# The realtime hook default follows the tracing switch: without an Opik
# server there is nothing for the hook to talk to. An explicit value wins.
if harbor_trace_to_opik_enabled; then
  HARBOR_CC_OPIK_ENABLE_HOOK="${HARBOR_CC_OPIK_ENABLE_HOOK:-1}"
else
  HARBOR_CC_OPIK_ENABLE_HOOK="${HARBOR_CC_OPIK_ENABLE_HOOK:-0}"
fi
TRACE_PLUGIN_SOURCE_DIR="${TRACE_PLUGIN_SOURCE_DIR:-$REPO_ROOT/third_party/agent-opik-plugin}"
TRACE_PLUGIN_CLAUDE_HOOK_SOURCE="${TRACE_PLUGIN_CLAUDE_HOOK_SOURCE:-$TRACE_PLUGIN_SOURCE_DIR/src/sii_opik_plugin/claude_code/claude_realtime_trace.py}"
TRACE_PLUGIN_OPENCODE_PLUGIN_SOURCE="${TRACE_PLUGIN_OPENCODE_PLUGIN_SOURCE:-$TRACE_PLUGIN_SOURCE_DIR/harness/opencode/opik-trace.ts}"
TRACE_PLUGIN_OPENCODE_HOOK_SOURCE="${TRACE_PLUGIN_OPENCODE_HOOK_SOURCE:-$TRACE_PLUGIN_SOURCE_DIR/src/sii_opik_plugin/opencode/opencode_realtime_trace.py}"
HARBOR_CC_HOOK_SOURCE="${HARBOR_CC_HOOK_SOURCE:-$TRACE_PLUGIN_CLAUDE_HOOK_SOURCE}"
HARBOR_CC_HOOK_MOUNT_PATH="${HARBOR_CC_HOOK_MOUNT_PATH:-/opt/tb-opik/claude_realtime_trace.py}"
HARBOR_CC_CLAUDE_TGZ_SOURCE="${HARBOR_CC_CLAUDE_TGZ_SOURCE:-${LOCAL_WHEEL_DIR}/${CLAUDE_CODE_TGZ_BASENAME}}"
HARBOR_CC_CLAUDE_TGZ_MOUNT_PATH="${HARBOR_CC_CLAUDE_TGZ_MOUNT_PATH:-/opt/tb-opik/claude-code.tgz}"
HARBOR_CC_PY_WHEEL_DIR_SOURCE="${HARBOR_CC_PY_WHEEL_DIR_SOURCE:-$LOCAL_WHEEL_DIR}"
HARBOR_CC_PY_WHEEL_DIR_MOUNT_PATH="${HARBOR_CC_PY_WHEEL_DIR_MOUNT_PATH:-/opt/tb-opik/python-wheels}"
HARBOR_CC_NPM_CACHE_MOUNT_PATH="${HARBOR_CC_NPM_CACHE_MOUNT_PATH:-${HARBOR_CC_PY_WHEEL_DIR_MOUNT_PATH}/npm-cache}"
HARBOR_CC_WEB_MCP_SOURCE="${HARBOR_CC_WEB_MCP_SOURCE:-}"
HARBOR_CC_WEB_MCP_MOUNT_PATH="${HARBOR_CC_WEB_MCP_MOUNT_PATH:-/opt/agent-fleet/exa_web_mcp.py}"
HARBOR_VERIFIER_UV_HOME="${HARBOR_VERIFIER_UV_HOME:-}"
HARBOR_VERIFIER_UV_BIN_DIR_MOUNT_PATH="${HARBOR_VERIFIER_UV_BIN_DIR_MOUNT_PATH:-/opt/tb-uv-backup/bin}"
HARBOR_E2B_VERIFIER_UV_SOURCE="${HARBOR_E2B_VERIFIER_UV_SOURCE:-}"
HARBOR_CC_OPIK_DEBUG="${HARBOR_CC_OPIK_DEBUG:-$CC_OPIK_DEBUG}"
HARBOR_CC_OPIK_INSTALL_DEPS="${HARBOR_CC_OPIK_INSTALL_DEPS:-true}"
# Package-source canonical name. Resolve its backend-specific default after
# HARBOR_ENVIRONMENT_TYPE is known; explicit saved or runtime values remain intact.
NPM_CONFIG_REGISTRY="${NPM_CONFIG_REGISTRY:-}"
GO111MODULE="${GO111MODULE:-on}"
GOPROXY="${GOPROXY:-https://goproxy.cn,direct}"
GOSUMDB="${GOSUMDB:-sum.golang.google.cn}"
RUSTUP_UPDATE_ROOT="${RUSTUP_UPDATE_ROOT:-https://mirrors.tuna.tsinghua.edu.cn/rustup/rustup}"
RUSTUP_DIST_SERVER="${RUSTUP_DIST_SERVER:-https://mirrors.tuna.tsinghua.edu.cn/rustup}"
CARGO_REGISTRY_REPLACE_WITH="${CARGO_REGISTRY_REPLACE_WITH:-mirror}"
CARGO_REGISTRY_URL="${CARGO_REGISTRY_URL:-sparse+https://mirrors.tuna.tsinghua.edu.cn/crates.io-index/}"
PIP_INDEX_URL="${PIP_INDEX_URL:-https://pypi.org/simple/}"
PIP_EXTRA_INDEX_URL="${PIP_EXTRA_INDEX_URL:-}"
PIP_TRUSTED_HOST="${PIP_TRUSTED_HOST:-}"

# OpenSandbox must always resolve to an explicit YiCloud environment. Keep the
# values empty in the public template; harboropik.sh fails before any API call
# when neither an immutable ID nor an exact environment name is configured.
YICLOUD_SANDBOX_ENVIRONMENT_ID="${YICLOUD_SANDBOX_ENVIRONMENT_ID:-}"
YICLOUD_SANDBOX_ENVIRONMENT_NAME="${YICLOUD_SANDBOX_ENVIRONMENT_NAME:-}"
YICLOUD_SANDBOX_READY_TIMEOUT_SEC="${YICLOUD_SANDBOX_READY_TIMEOUT_SEC:-300}"
YICLOUD_SANDBOX_STATUS_LOG_INTERVAL_SEC="${YICLOUD_SANDBOX_STATUS_LOG_INTERVAL_SEC:-30}"
YICLOUD_SANDBOX_RETAIN_ON_START_FAILURE="${YICLOUD_SANDBOX_RETAIN_ON_START_FAILURE:-0}"
YICLOUD_SANDBOX_RETAIN_AFTER_TRIAL="${YICLOUD_SANDBOX_RETAIN_AFTER_TRIAL:-0}"
YICLOUD_SANDBOX_PROXY_ORIGIN="${YICLOUD_SANDBOX_PROXY_ORIGIN:-}"
YICLOUD_SANDBOX_FAST_UPLOAD_ORIGIN="${YICLOUD_SANDBOX_FAST_UPLOAD_ORIGIN-https://sandbox.yicloud.com.cn}"
YICLOUD_SANDBOX_UPLOAD_TIMEOUT_SEC="${YICLOUD_SANDBOX_UPLOAD_TIMEOUT_SEC:-1800}"
YICLOUD_SANDBOX_S3_PROFILE="${YICLOUD_SANDBOX_S3_PROFILE:-}"
harbor_resolve_opensandbox_s3_profile "$REPO_ROOT"
YICLOUD_SANDBOX_UPLOAD_BACKEND="${YICLOUD_SANDBOX_UPLOAD_BACKEND:-http}"
YICLOUD_SANDBOX_S3_CONFIG="${YICLOUD_SANDBOX_S3_CONFIG:-}"
YICLOUD_SANDBOX_S3_BUCKET="${YICLOUD_SANDBOX_S3_BUCKET:-}"
YICLOUD_SANDBOX_S3_READ_ORIGIN="${YICLOUD_SANDBOX_S3_READ_ORIGIN:-}"
YICLOUD_SANDBOX_S3_PREFIX="${YICLOUD_SANDBOX_S3_PREFIX:-agent-fleet-upload/v1}"
YICLOUD_SANDBOX_S3_CACHE_ROOT="${YICLOUD_SANDBOX_S3_CACHE_ROOT:-${RUNTIME_DIR}/s3-upload-cache}"
YICLOUD_SANDBOX_S3_LOCK_ROOT="${YICLOUD_SANDBOX_S3_LOCK_ROOT:-${RUNTIME_DIR}/s3-upload-locks}"
YICLOUD_SANDBOX_S3_DOWNLOAD_TIMEOUT_SEC="${YICLOUD_SANDBOX_S3_DOWNLOAD_TIMEOUT_SEC:-1800}"
YICLOUD_SANDBOX_S3_DIRECTORY_COMPRESSION="${YICLOUD_SANDBOX_S3_DIRECTORY_COMPRESSION:-auto}"
YICLOUD_SANDBOX_S3CMD="${YICLOUD_SANDBOX_S3CMD:-${HARBOR_RUNNER_DIR}/bin/s3cmd}"
YICLOUD_SANDBOX_CPU="${YICLOUD_SANDBOX_CPU:-2}"
YICLOUD_SANDBOX_MEMORY="${YICLOUD_SANDBOX_MEMORY:-8Gi}"
YICLOUD_SANDBOX_LIFECYCLE_MINUTES="${YICLOUD_SANDBOX_LIFECYCLE_MINUTES:-120}"
export YICLOUD_SANDBOX_ENVIRONMENT_ID YICLOUD_SANDBOX_ENVIRONMENT_NAME
export YICLOUD_SANDBOX_READY_TIMEOUT_SEC
export YICLOUD_SANDBOX_STATUS_LOG_INTERVAL_SEC
export YICLOUD_SANDBOX_RETAIN_ON_START_FAILURE
export YICLOUD_SANDBOX_RETAIN_AFTER_TRIAL
export YICLOUD_SANDBOX_PROXY_ORIGIN
export YICLOUD_SANDBOX_FAST_UPLOAD_ORIGIN
export YICLOUD_SANDBOX_UPLOAD_TIMEOUT_SEC YICLOUD_SANDBOX_UPLOAD_BACKEND
export YICLOUD_SANDBOX_S3_PROFILE
export YICLOUD_SANDBOX_S3_CONFIG YICLOUD_SANDBOX_S3_BUCKET
export YICLOUD_SANDBOX_S3_READ_ORIGIN
export YICLOUD_SANDBOX_S3_PREFIX YICLOUD_SANDBOX_S3_CACHE_ROOT
export YICLOUD_SANDBOX_S3_LOCK_ROOT
export YICLOUD_SANDBOX_S3_DOWNLOAD_TIMEOUT_SEC
export YICLOUD_SANDBOX_S3_DIRECTORY_COMPRESSION
export YICLOUD_SANDBOX_S3CMD
export YICLOUD_SANDBOX_CPU YICLOUD_SANDBOX_MEMORY
export YICLOUD_SANDBOX_LIFECYCLE_MINUTES

# qz (SII Inspire) E2B-compatible sandbox connection. Values usually come from
# config.local.env; re-export here so shell-provided values survive into
# worker panes. The qz adapter maps SBX_*/QZ_SANDBOX_* onto the official e2b
# SDK. Those qz values override ambient cloud-E2B connection and transport
# settings inside a qz process; E2B_API_KEY remains a fallback only when it
# contains an sbx_-prefixed qz key.
QZ_SANDBOX_API_KEY="${QZ_SANDBOX_API_KEY:-}"
QZ_SANDBOX_API_URL="${QZ_SANDBOX_API_URL:-}"
QZ_SANDBOX_TEMPLATE="${QZ_SANDBOX_TEMPLATE:-}"
QZ_SANDBOX_TEMPLATE_MAP="${QZ_SANDBOX_TEMPLATE_MAP:-}"
QZ_SANDBOX_TIMEOUT_SEC="${QZ_SANDBOX_TIMEOUT_SEC:-}"
SBX_API_KEY="${SBX_API_KEY:-}"
SBX_API_URL="${SBX_API_URL:-}"
export QZ_SANDBOX_API_KEY QZ_SANDBOX_API_URL QZ_SANDBOX_TEMPLATE
export QZ_SANDBOX_TEMPLATE_MAP
export QZ_SANDBOX_TIMEOUT_SEC SBX_API_KEY SBX_API_URL

UV_INDEX_URL="${UV_INDEX_URL:-$PIP_INDEX_URL}"
UV_DEFAULT_INDEX="${UV_DEFAULT_INDEX:-$UV_INDEX_URL}"

HARBOR_PIP_DEFAULT_TIMEOUT="${HARBOR_PIP_DEFAULT_TIMEOUT:-120}"
HARBOR_PIP_RETRIES="${HARBOR_PIP_RETRIES:-10}"
HARBOR_SKIP_DOCKERHUB_PREFLIGHT="${HARBOR_SKIP_DOCKERHUB_PREFLIGHT:-0}"
HARBOR_DOCKERHUB_CHECK_TIMEOUT="${HARBOR_DOCKERHUB_CHECK_TIMEOUT:-8}"
HARBOR_DOCKERHUB_PREFLIGHT_STRICT="${HARBOR_DOCKERHUB_PREFLIGHT_STRICT:-0}"
SMITH_GENERATE_IF_MISSING="${SMITH_GENERATE_IF_MISSING:-1}"
SMITH_ADAPTER_DIR="${SMITH_ADAPTER_DIR:-$HARBOR_ROOT/adapters/swesmith}"
FIX_GIT_IMAGE_NAME="${FIX_GIT_IMAGE_NAME:-xiangyangli/fix-git:20260204}"
FIX_GIT_WARM_LABEL="${FIX_GIT_WARM_LABEL:-io.codex.prewarmed}"

# ── opencode agent ────────────────────────────────────────────────────────────
OPENCODE_VERSION="${OPENCODE_VERSION:-latest}"
OPENCODE_TGZ_BASENAME="${OPENCODE_TGZ_BASENAME:-opencode-ai-${OPENCODE_VERSION}.tgz}"
OPENCODE_LINUX_X64_TGZ_BASENAME="${OPENCODE_LINUX_X64_TGZ_BASENAME:-opencode-linux-x64-${OPENCODE_VERSION}.tgz}"
OPENCODE_CONFIG_CONTENT="${OPENCODE_CONFIG_CONTENT:-}"
OPENCODE_RUNTIME_SECRETS_JSON="${OPENCODE_RUNTIME_SECRETS_JSON:-}"
if [[ -z "$OPENCODE_RUNTIME_SECRETS_JSON" ]]; then
  OPENCODE_RUNTIME_SECRETS_JSON="{}"
fi
OPENCODE_HAS_REQUEST_HEADERS="0"
if [[ "$AGENT" == "opencode" ]]; then
  OPENCODE_RUNTIME_SECRETS_JSON="$(
    OPENCODE_RUNTIME_SECRETS_JSON="$OPENCODE_RUNTIME_SECRETS_JSON" \
    HARBOR_ANTHROPIC_AUTH_TOKEN="$HARBOR_ANTHROPIC_AUTH_TOKEN" \
    HARBOR_LLM_KWARGS="$HARBOR_LLM_KWARGS" \
    HARBOR_MODEL="$HARBOR_MODEL" \
    OPENCODE_CONFIG_CONTENT="$OPENCODE_CONFIG_CONTENT" \
      python3 "$SCRIPT_DIR/env.py" opencode-runtime-secrets
  )"
  if [[ -n "$OPENCODE_CONFIG_CONTENT" ]]; then
    OPENCODE_CONFIG_CONTENT="$(
      OPENCODE_CONFIG_CONTENT="$OPENCODE_CONFIG_CONTENT" \
        python3 "$SCRIPT_DIR/env.py" opencode-sanitize-config
    )"
  fi
  OPENCODE_HAS_REQUEST_HEADERS="$(
    HARBOR_LLM_KWARGS="$HARBOR_LLM_KWARGS" \
      python3 "$SCRIPT_DIR/env.py" has-model-request-headers
  )"
fi
if [[ "$AGENT" == "opencode" \
  && ( ( -z "$OPENCODE_CONFIG_CONTENT" && "${HARBOR_MODEL%%/*}" == "custom" ) \
    || -n "$HARBOR_TEMPERATURE" \
    || -n "$HARBOR_TOP_P" \
    || -n "$HARBOR_MAX_TOKENS" \
    || "$OPENCODE_HAS_REQUEST_HEADERS" == "1" ) ]]; then
  # OpenCode's built-in minimax provider ignores our gateway BASE_URL and calls
  # api.minimax.io directly. Use an OpenAI-compatible custom provider by default.
  OPENCODE_CONFIG_CONTENT="$(
    HARBOR_ANTHROPIC_BASE_URL="$HARBOR_ANTHROPIC_BASE_URL" \
    HARBOR_LLM_KWARGS="$HARBOR_LLM_KWARGS" \
    HARBOR_MODEL="$HARBOR_MODEL" \
    HARBOR_TEMPERATURE="$HARBOR_TEMPERATURE" \
    HARBOR_TOP_P="$HARBOR_TOP_P" \
    HARBOR_MAX_TOKENS="$HARBOR_MAX_TOKENS" \
    OPENCODE_CONFIG_CONTENT="$OPENCODE_CONFIG_CONTENT" \
      python3 "$SCRIPT_DIR/env.py" opencode-config
  )"
fi

NEXT_INDEX_FILE="${QUEUE_DIR}/next_index"
LOCK_FILE="${QUEUE_DIR}/.queue.lock"
WORKERS_READY_FILE="${RUNTIME_DIR}/workers.ready"
WORKERS_FAILED_FILE="${RUNTIME_DIR}/workers.failed"

# ── RL rollout mode ──────────────────────────────────────────────────────────
# Keep RL-specific implementation outside common/Harbor; Harbor only exposes the
# start.sh entry point and shared benchmark/runtime configuration.
RL_UTILS_DIR="${RL_UTILS_DIR:-$REPO_ROOT/Agents/utils/rl}"
RL_ENV_FILE="${RL_ENV_FILE:-$RL_UTILS_DIR/RL-env.sh}"
if [[ "$ROLLOUT" == "1" && -f "$RL_ENV_FILE" ]]; then
  RL_MODEL_NAME="${RL_MODEL_NAME:-$_HARBOR_EFFECTIVE_MODEL}"
  RL_API_BASE="${RL_API_BASE:-${HARBOR_ANTHROPIC_BASE_URL:+${HARBOR_ANTHROPIC_BASE_URL}/v1}}"
  RL_API_KEY="${RL_API_KEY:-$HARBOR_ANTHROPIC_AUTH_TOKEN}"
  # shellcheck source=/dev/null
  . "$RL_ENV_FILE"
fi
RL_HOST="${RL_HOST:-0.0.0.0}"
RL_PORT="${RL_PORT:-19001}"
RL_DATASET_NAME="${RL_DATASET_NAME:-$DATASET_NAME}"
if [[ "$RL_DATASET_NAME" == "auto" ]]; then
  RL_DATASET_NAME="seta"
fi
RL_DATASET_ROOT="${RL_DATASET_ROOT:-$DATASET_PATH}"
RL_DATASET_ROOTS="${RL_DATASET_ROOTS:-}"
RL_TRIALS_DIR="${RL_TRIALS_DIR:-${OUTPUT_ROOT}/rl-remote-trials}"
RL_MAX_CONCURRENT="${RL_MAX_CONCURRENT:-16}"
RL_AGENT="${RL_AGENT:-claude-code}"
RL_MODEL_NAME="${RL_MODEL_NAME:-$_HARBOR_EFFECTIVE_MODEL}"
RL_MODEL_PREFIX="${RL_MODEL_PREFIX:-hosted_vllm}"
if [[ -z "${RL_API_BASE:-}" && -n "${BASE_URL:-}" ]]; then
  RL_API_BASE="${BASE_URL%/}/v1"
fi
RL_API_BASE="${RL_API_BASE:-}"
RL_API_KEY="${RL_API_KEY:-$API_KEY}"
RL_API_KEY_MODE="${RL_API_KEY_MODE:-static}"
MODEL_REQUEST_CONFIG_JSON="${MODEL_REQUEST_CONFIG_JSON:-}"
RL_DISABLED_TASK_IDS="${RL_DISABLED_TASK_IDS:-}"
RL_ENVIRONMENT_TYPE="${RL_ENVIRONMENT_TYPE:-docker}"
RL_E2B_SANDBOX_TIMEOUT_SEC="${RL_E2B_SANDBOX_TIMEOUT_SEC:-}"
RL_E2B_PREBUILT_TEMPLATE="${RL_E2B_PREBUILT_TEMPLATE:-}"
HARBOR_ENVIRONMENT_TYPE="${HARBOR_ENVIRONMENT_TYPE:-$RL_ENVIRONMENT_TYPE}"
HARBOR_E2B_SANDBOX_TIMEOUT_SEC="${HARBOR_E2B_SANDBOX_TIMEOUT_SEC:-$RL_E2B_SANDBOX_TIMEOUT_SEC}"
HARBOR_E2B_PREBUILT_TEMPLATE="${HARBOR_E2B_PREBUILT_TEMPLATE:-${RL_E2B_PREBUILT_TEMPLATE:-${E2B_TEMPLATE:-}}}"
HARBOR_E2B_PREBUILT_ENVIRONMENT_SPEC="${HARBOR_E2B_PREBUILT_ENVIRONMENT_SPEC:-e2b_prebuilt:PrebuiltE2BEnvironment}"
RL_FORCE_BUILD="${RL_FORCE_BUILD:-$HARBOR_FORCE_BUILD}"
RL_TRACE_LOG="${RL_TRACE_LOG:-${RUNTIME_DIR}/rl-rollout-requests.jsonl}"
RL_SERVER_LOG="${RL_SERVER_LOG:-${RUNTIME_DIR}/rl-rollout-server.log}"
RL_SERVER_PID_FILE="${RL_SERVER_PID_FILE:-${RUNTIME_DIR}/rl-rollout-server.pid}"
RL_QUEUE_DIR="${RL_QUEUE_DIR:-${RUNTIME_DIR}/rl-queue}"
RL_ACTIVE_DIR="${RL_ACTIVE_DIR:-${RL_QUEUE_DIR}/active}"
RL_JOB_QUEUE_ROOT="${RL_JOB_QUEUE_ROOT:-${RL_QUEUE_DIR}/jobs}"
RL_JOB_RUNTIME_ROOT="${RL_JOB_RUNTIME_ROOT:-${RUNTIME_DIR}/rl-jobs}"
RL_DYNAMIC_JOB_ZELLIJ="${RL_DYNAMIC_JOB_ZELLIJ:-1}"
RL_JOB_ZELLIJ_START_TIMEOUT="${RL_JOB_ZELLIJ_START_TIMEOUT:-120}"
RL_JOB_ZELLIJ_LOCK_TIMEOUT="${RL_JOB_ZELLIJ_LOCK_TIMEOUT:-30}"
RL_JOB_ZELLIJ_READY_TIMEOUT="${RL_JOB_ZELLIJ_READY_TIMEOUT:-90}"
RL_WORKERS="${RL_WORKERS:-${RL_MAX_CONCURRENT:-$TOTAL_WORKERS}}"
RL_REQUEST_TIMEOUT="${RL_REQUEST_TIMEOUT:-3600}"
RL_KEEP_TRIALS_PER_WORKER="${RL_KEEP_TRIALS_PER_WORKER:-20}"
RL_MODEL_INFO="${RL_MODEL_INFO:-$HARBOR_MODEL_INFO}"
RL_MAX_NEW_TOKENS="${RL_MAX_NEW_TOKENS:-}"
RL_CLAUDE_CODE_MAX_OUTPUT_TOKENS="${RL_CLAUDE_CODE_MAX_OUTPUT_TOKENS:-}"
RL_MAX_TURNS="${RL_MAX_TURNS:-32}"
RL_AGENT_TIMEOUT_MULTIPLIER="${RL_AGENT_TIMEOUT_MULTIPLIER:-$HARBOR_AGENT_TIMEOUT_MULTIPLIER}"
RL_LLM_TIMEOUT="${RL_LLM_TIMEOUT:-900}"
RL_LLM_MAX_RETRIES="${RL_LLM_MAX_RETRIES:-0}"
RL_TEMPERATURE="${RL_TEMPERATURE:-1.0}"
RL_TOP_P="${RL_TOP_P:-1.0}"
RL_TOP_K="${RL_TOP_K:--1}"
RL_MIN_P="${RL_MIN_P:-0.0}"
RL_COLLECT_ROLLOUT_DETAILS="${RL_COLLECT_ROLLOUT_DETAILS:-true}"
RL_ENABLE_SUMMARIZE="${RL_ENABLE_SUMMARIZE:-false}"

# Harbor accepts either a built-in environment name or a module:Class import
# path. YiCloud uses its own OpenAPI SDK and OGW signing, so it is loaded as a
# provider adapter without patching the PyPI Harbor package. qz (SII Inspire)
# exposes an E2B-compatible control plane, so its adapter reuses Harbor's E2B
# environment with qz connection settings mapped onto the official e2b SDK.
HARBOR_ENVIRONMENT_TYPE="${HARBOR_ENVIRONMENT_TYPE:-$RL_ENVIRONMENT_TYPE}"
if [[ -z "${HARBOR_ENVIRONMENT_SPEC:-}" ]]; then
  if [[ "$HARBOR_ENVIRONMENT_TYPE" == "opensandbox" ]]; then
    HARBOR_ENVIRONMENT_SPEC="yicloud_opensandbox:YiCloudOpenSandboxEnvironment"
  elif [[ "$HARBOR_ENVIRONMENT_TYPE" == "e2b" && -n "$HARBOR_E2B_PREBUILT_TEMPLATE" ]]; then
    HARBOR_ENVIRONMENT_SPEC="$HARBOR_E2B_PREBUILT_ENVIRONMENT_SPEC"
  elif [[ "$HARBOR_ENVIRONMENT_TYPE" == "qz" ]]; then
    HARBOR_ENVIRONMENT_SPEC="qz_e2b_sandbox:QzSandboxEnvironment"
  else
    HARBOR_ENVIRONMENT_SPEC="$HARBOR_ENVIRONMENT_TYPE"
  fi
fi
# qz does not provide Notebook-host bind mounts. Install the agent runtime
# inside the Sandbox instead of coupling setup to a runner-local dependency
# service. npmmirror is the regional-stability default, not the only reachable
# source: NPM_CONFIG_REGISTRY and QZ_NODE_DIST_URL allow an explicit upstream
# or private source. HARBOR_CC_NODE_DIST_URL reaches the agent as CC_NODE_DIST_URL.
QZ_NODE_DIST_URL="${QZ_NODE_DIST_URL:-}"
HARBOR_CC_NODE_DIST_URL="${HARBOR_CC_NODE_DIST_URL:-}"
if [[ -z "$NPM_CONFIG_REGISTRY" ]]; then
  if [[ "$HARBOR_ENVIRONMENT_TYPE" == "qz" ]]; then
    NPM_CONFIG_REGISTRY="https://registry.npmmirror.com"
  else
    NPM_CONFIG_REGISTRY="https://registry.npmjs.org"
  fi
fi
if [[ "$HARBOR_ENVIRONMENT_TYPE" == "qz" ]]; then
  if [[ -n "$QZ_NODE_DIST_URL" ]]; then
    HARBOR_CC_NODE_DIST_URL="$QZ_NODE_DIST_URL"
  elif [[ -z "$HARBOR_CC_NODE_DIST_URL" ]]; then
    HARBOR_CC_NODE_DIST_URL="https://registry.npmmirror.com/-/binary/node/v22.14.0/node-v22.14.0-linux-x64.tar.gz"
  fi
fi
export QZ_NODE_DIST_URL HARBOR_CC_NODE_DIST_URL
HARBOR_OPENSANDBOX_IMAGE_REF="${HARBOR_OPENSANDBOX_IMAGE_REF:-}"
HARBOR_OPENSANDBOX_BUNDLE_MANIFEST="${HARBOR_OPENSANDBOX_BUNDLE_MANIFEST:-}"
YICLOUD_HARBOR_HOST="${YICLOUD_HARBOR_HOST:-}"
# Harbor Project is an externally provisioned benchmark mapping. A task
# repository is derived per task by the manager; never use a fixed repository.
YICLOUD_HARBOR_PROJECT="${YICLOUD_HARBOR_PROJECT:-}"
YICLOUD_HARBOR_TLS_VERIFY="${YICLOUD_HARBOR_TLS_VERIFY:-0}"
HARBOR_OPENSANDBOX_BENCHMARK="${HARBOR_OPENSANDBOX_BENCHMARK:-$DATASET_NAME}"

# Keep benchmark-specific verifier runtime policy in this thin selector. The
# OpenSandbox provider treats the selected archive as an opaque filesystem
# bundle and does not know which runtimes it contains.
select_verifier_runtime_bundle() {
  if [[ "$HARBOR_ENVIRONMENT_TYPE" != "opensandbox" ]]; then
    printf '%s\n' "none"
    return 0
  fi
  case "$HARBOR_OPENSANDBOX_BENCHMARK" in
    agent-fleet-swe-rebench-v2)
      printf '%s\n' "agent-fleet-swe-rebench-v2-verifier-bundle"
      ;;
    *)
      printf '%s\n' "none"
      ;;
  esac
}

resolve_verifier_runtime_bundle() {
  VERIFIER_RUNTIME_BUNDLE_ID="$1"
  VERIFIER_RUNTIME_BUNDLE_ARCHIVE_SOURCE=""
  VERIFIER_RUNTIME_BUNDLE_ARCHIVE_MOUNT_PATH=""
  VERIFIER_RUNTIME_BUNDLE_ROOT=""
  VERIFIER_RUNTIME_BUNDLE_PREPARER=""
  case "$VERIFIER_RUNTIME_BUNDLE_ID" in
    none)
      ;;
    agent-fleet-swe-rebench-v2-verifier-bundle)
      VERIFIER_RUNTIME_BUNDLE_ARCHIVE_SOURCE="$HARBOR_CC_PY_WHEEL_DIR_SOURCE/$VERIFIER_RUNTIME_BUNDLE_ID.tar.gz"
      VERIFIER_RUNTIME_BUNDLE_ARCHIVE_MOUNT_PATH="$HARBOR_CC_PY_WHEEL_DIR_MOUNT_PATH/$VERIFIER_RUNTIME_BUNDLE_ID.tar.gz"
      VERIFIER_RUNTIME_BUNDLE_ROOT="/tmp/harbor-verifier-bundles/$VERIFIER_RUNTIME_BUNDLE_ID"
      VERIFIER_RUNTIME_BUNDLE_PREPARER="$SCRIPT_DIR/verifier_runtime/swe_rebench_v2_bundle_preparer.py"
      ;;
    *)
      echo "[ERROR] unknown verifier runtime bundle: $VERIFIER_RUNTIME_BUNDLE_ID" >&2
      return 1
      ;;
  esac
}

resolve_verifier_runtime_bundle "$(select_verifier_runtime_bundle)"

verifier_runtime_bundle_required() {
  [[ "$VERIFIER_RUNTIME_BUNDLE_ID" != "none" ]]
}

validate_verifier_runtime_bundle_transport() {
  verifier_runtime_bundle_required || return 0
  case "$YICLOUD_SANDBOX_UPLOAD_BACKEND" in
    s3|auto)
      ;;
    *)
      echo "[ERROR] verifier runtime bundle $VERIFIER_RUNTIME_BUNDLE_ID requires YICLOUD_SANDBOX_UPLOAD_BACKEND=s3 or auto" >&2
      return 1
      ;;
  esac
}

HARBOR_OPENSANDBOX_DOCKER_CONFIG="${HARBOR_OPENSANDBOX_DOCKER_CONFIG:-$HOME/.docker/config.json}"
HARBOR_OPENSANDBOX_IMAGE_CACHE_ROOT="${HARBOR_OPENSANDBOX_IMAGE_CACHE_ROOT:-/data/harbor-runs/opensandbox-images}"
HARBOR_OPENSANDBOX_IMAGE_PLATFORM="${HARBOR_OPENSANDBOX_IMAGE_PLATFORM:-linux/amd64}"
HARBOR_OPENSANDBOX_IMAGE_TAG_PREFIX="${HARBOR_OPENSANDBOX_IMAGE_TAG_PREFIX:-harbor}"
HARBOR_OPENSANDBOX_DOCKERHUB_MIRROR_PREFIX="${HARBOR_OPENSANDBOX_DOCKERHUB_MIRROR_PREFIX:-m.daocloud.io/docker.io}"
HARBOR_OPENSANDBOX_APT_MIRROR="${HARBOR_OPENSANDBOX_APT_MIRROR:-http://mirrors.tuna.tsinghua.edu.cn}"
HARBOR_OPENSANDBOX_PIP_INDEX_URL="${HARBOR_OPENSANDBOX_PIP_INDEX_URL:-https://pypi.tuna.tsinghua.edu.cn/simple}"
HARBOR_OPENSANDBOX_NPM_REGISTRY="${HARBOR_OPENSANDBOX_NPM_REGISTRY:-https://registry.npmmirror.com}"
HARBOR_OPENSANDBOX_GOPROXY="${HARBOR_OPENSANDBOX_GOPROXY:-https://goproxy.cn,direct}"
HARBOR_OPENSANDBOX_GOSUMDB="${HARBOR_OPENSANDBOX_GOSUMDB:-sum.golang.google.cn}"
HARBOR_OPENSANDBOX_CARGO_REGISTRY_URL="${HARBOR_OPENSANDBOX_CARGO_REGISTRY_URL:-sparse+https://mirrors.tuna.tsinghua.edu.cn/crates.io-index/}"
HARBOR_OPENSANDBOX_RUSTUP_DIST_SERVER="${HARBOR_OPENSANDBOX_RUSTUP_DIST_SERVER:-https://mirrors.tuna.tsinghua.edu.cn/rustup}"
HARBOR_OPENSANDBOX_RUSTUP_UPDATE_ROOT="${HARBOR_OPENSANDBOX_RUSTUP_UPDATE_ROOT:-https://mirrors.tuna.tsinghua.edu.cn/rustup/rustup}"
HARBOR_OPENSANDBOX_GITHUB_MIRROR_URL="${HARBOR_OPENSANDBOX_GITHUB_MIRROR_URL:-}"
HARBOR_OPENSANDBOX_RUSTUP_INIT_URL="${HARBOR_OPENSANDBOX_RUSTUP_INIT_URL:-}"
HARBOR_OPENSANDBOX_PYTORCH_INDEX_URL="${HARBOR_OPENSANDBOX_PYTORCH_INDEX_URL:-}"
HARBOR_OPENSANDBOX_PACKAGE_SOURCE_HEALTH_URL="${HARBOR_OPENSANDBOX_PACKAGE_SOURCE_HEALTH_URL:-}"
HARBOR_OPENSANDBOX_BUILD_ARGS_JSON="${HARBOR_OPENSANDBOX_BUILD_ARGS_JSON:-}"
if [[ -z "${HARBOR_OPENSANDBOX_BUILD_ARGS_JSON}" ]]; then
  HARBOR_OPENSANDBOX_BUILD_ARGS_JSON='{}'
fi
HARBOR_OPENSANDBOX_BUILD_USE_PROXY="${HARBOR_OPENSANDBOX_BUILD_USE_PROXY:-1}"
HARBOR_OPENSANDBOX_BUILD_NETWORK="${HARBOR_OPENSANDBOX_BUILD_NETWORK:-host}"
HARBOR_OPENSANDBOX_BUILD_PROXY_URL="${HARBOR_OPENSANDBOX_BUILD_PROXY_URL:-}"
HARBOR_OPENSANDBOX_IMAGE_MANAGER="${HARBOR_OPENSANDBOX_IMAGE_MANAGER:-$SCRIPT_DIR/opensandbox_image_manager.py}"

export SCRIPT_DIR REPO_ROOT AGENTS_DIR TASKS_DIR HARBOR_CLAUDE_CODE_DIR HARBOR_OPENCODE_DIR HARBOR_PI_DIR WORKSPACE_DIR RUN_ID TOTAL_WORKERS N_ATTEMPTS MODEL AGENT MAX_RETRIES
export HARBOR_ROOT DATASET_PATH DATASET_NAME METRIC_MODE OUTPUT_ROOT OUTPUT_PATH TASK_SOURCE_FILE TASK_FILE FLEET_TASKS QUEUE_DIR RUNTIME_DIR LAYOUT_FILE JOBS_ROOT
export HARBOR_ONLINE_ANALYSIS HARBOR_ONLINE_ANALYSIS_POLL_INTERVAL HARBOR_ONLINE_ANALYSIS_DIR HARBOR_ONLINE_ANALYSIS_PID_FILE HARBOR_ONLINE_ANALYSIS_LOG_FILE HARBOR_EARLY_STOP HARBOR_ZELLIJ_CLOSE_ON_COMPLETE HARBOR_ZELLIJ_KEEP_ON_FAILURE
export HARBOR_MONITOR_ENABLED HARBOR_MONITOR_DIR HARBOR_MONITOR_PID_FILE HARBOR_MONITOR_LOG_FILE HARBOR_BENCHMARK_PID_FILE HARBOR_BENCHMARK_EXIT_FILE HARBOR_JOB_DIR_FILE HARBOR_MONITOR_RESTART_CMD HARBOR_MONITOR_STOP_CMD HARBOR_MONITOR_INTERVAL HARBOR_MONITOR_STARTUP_GRACE HARBOR_MONITOR_STALL_SECONDS HARBOR_MONITOR_MAX_RETRIES HARBOR_MONITOR_CONFIGURED_TIMEOUT
export API_KEY BASE_URL HARBOR_ANALYZER_API_KEY HARBOR_ANALYZER_BASE_URL HARBOR_ANALYZER_MODEL HARBOR_ANALYZER_PI_PROVIDER HARBOR_ANALYZER_NO_PROXY HARBOR_ANALYZER_ENABLED HARBOR_ANALYZER_MODE HARBOR_ANALYZER_OUTPUT_DIR HARBOR_ANALYZER_PID_FILE HARBOR_ANALYZER_SUPERVISOR_PID_FILE HARBOR_ANALYZER_SUPERVISOR_ID_FILE HARBOR_ANALYZER_LOG_FILE HARBOR_ANALYZER_POLL_INTERVAL HARBOR_ANALYZER_TIMEOUT HARBOR_ANALYZER_MAX_CONCURRENCY HARBOR_FIXER_API_KEY HARBOR_FIXER_BASE_URL HARBOR_FIXER_MODEL HARBOR_FIXER_PI_BIN HARBOR_FIXER_PI_PROVIDER HARBOR_FIXER_NO_PROXY HARBOR_FIXER_AGENT_TIMEOUT HARBOR_FIXER_EXECUTION_TIMEOUT HARBOR_FIXER_SUMMARY_LIMIT HARBOR_FIXER_MAX_CONCURRENCY HARBOR_FIXER_MAX_TASK_SUMMARY_CHARS HARBOR_FIXER_MAX_TASK_SUMMARIES_CHARS OPIK_URL OPIK_URL_OVERRIDE OPIK_BASE OPIK_PROJECT_NAME OPIK_API_KEY OPIK_WORKSPACE CC_OPIK_DEBUG
export HARBOR_RUN_TIMESTAMP HARBOR_SESSION_TIMESTAMP HARBOR_RUN_AGENT_NAME HARBOR_RUN_DATASET_NAME HARBOR_RUN_MODEL_NAME HARBOR_ZELLIJ_SESSION_NAME
export CLAUDE_CODE_VERSION CLAUDE_CODE_TGZ_BASENAME LOCAL_WHEEL_DIR LOCAL_WHEEL_PORT LOCAL_WHEEL_PORT_ATTEMPTS LOCAL_WHEEL_HOST_IP
export PI_PROVIDER PI_VERSION PI_TGZ_BASENAME PI_NODE_RUNTIME_BASENAME PI_RUNTIME_BASENAME PI_THINKING_LEVEL PI_MODELS_CONFIG PI_SETTINGS_CONFIG PI_SUPPORTS_REASONING_EFFORT PI_THINKING_LEVEL_MAP PI_EXTENSION_SOURCE PI_EXTENSION_DIR
export HARBOR_LOCAL_WHEEL_SERVER_URL HARBOR_LOCAL_CLAUDE_TGZ_URL HARBOR_REMOTE_WHEEL_SERVER_URLS EFFECTIVE_WHEEL_URL_FILE EFFECTIVE_CLAUDE_TGZ_URL_FILE LOCAL_DEPS_LOG_FILE HARBOR_RUNNER_PREPARE HARBOR_RUNNER_IMAGE_DIR HARBOR_RUNNER_HOST_DIR HARBOR_RUNNER_PYTHON_VERSION HARBOR_RUNNER_DIR HARBOR_OPIK_BIN HARBOR_CLI_BIN HARBOR_OPIK_PYTHON HARBOR_RUNNER_REQUIREMENTS HARBOR_RUNNER_PREPARE_STATUS_FILE HARBOR_RUNNER_PREPARE_LOG_FILE
export HARBOR_LIMIT HARBOR_RUNS HARBOR_AGENT_IMPORT_PATH HARBOR_MODEL INCLUDE_TASKS HARBOR_DRY_RUN MIN_TEST MIN_TEST_INCLUDE_TASK
export HARBOR_ENVIRONMENT_TYPE HARBOR_ENVIRONMENT_SPEC HARBOR_OPENSANDBOX_IMAGE_REF HARBOR_OPENSANDBOX_BUNDLE_MANIFEST HARBOR_OPENSANDBOX_IMAGE_REPOSITORY HARBOR_OPENSANDBOX_SANDBOX_IMAGE_PREFIX HARBOR_OPENSANDBOX_DOCKER_CONFIG HARBOR_OPENSANDBOX_IMAGE_CACHE_ROOT HARBOR_OPENSANDBOX_IMAGE_PLATFORM HARBOR_OPENSANDBOX_IMAGE_TAG_PREFIX HARBOR_OPENSANDBOX_DOCKERHUB_MIRROR_PREFIX HARBOR_OPENSANDBOX_APT_MIRROR HARBOR_OPENSANDBOX_PIP_INDEX_URL HARBOR_OPENSANDBOX_NPM_REGISTRY HARBOR_OPENSANDBOX_GOPROXY HARBOR_OPENSANDBOX_GOSUMDB HARBOR_OPENSANDBOX_CARGO_REGISTRY_URL HARBOR_OPENSANDBOX_RUSTUP_DIST_SERVER HARBOR_OPENSANDBOX_RUSTUP_UPDATE_ROOT HARBOR_OPENSANDBOX_GITHUB_MIRROR_URL HARBOR_OPENSANDBOX_RUSTUP_INIT_URL HARBOR_OPENSANDBOX_PYTORCH_INDEX_URL HARBOR_OPENSANDBOX_PACKAGE_SOURCE_HEALTH_URL HARBOR_OPENSANDBOX_BUILD_ARGS_JSON HARBOR_OPENSANDBOX_BUILD_USE_PROXY HARBOR_OPENSANDBOX_BUILD_NETWORK HARBOR_OPENSANDBOX_BUILD_PROXY_URL HARBOR_OPENSANDBOX_IMAGE_MANAGER YICLOUD_HARBOR_HOST YICLOUD_HARBOR_PROJECT YICLOUD_HARBOR_TLS_VERIFY HARBOR_OPENSANDBOX_BENCHMARK
export HARBOR_E2B_SANDBOX_TIMEOUT_SEC HARBOR_E2B_PREBUILT_TEMPLATE HARBOR_E2B_PREBUILT_ENVIRONMENT_SPEC
export HARBOR_N_CONCURRENT HARBOR_MAX_RETRIES HARBOR_RETRY_INCLUDE_EXCEPTIONS HARBOR_RETRY_EXCLUDE_EXCEPTIONS HARBOR_AK_MAX_TURNS HARBOR_AK_COLLECT_ROLLOUT_DETAILS HARBOR_AK_ENABLE_SUMMARIZE HARBOR_DISALLOWED_TOOLS HARBOR_APPEND_SYSTEM_PROMPT
export HARBOR_TEMPERATURE HARBOR_TOP_P HARBOR_MAX_TOKENS
export HARBOR_API_BASE HARBOR_LLM_KWARGS HARBOR_MAX_NEW_TOKENS HARBOR_MODEL_INFO HARBOR_ANTHROPIC_BASE_URL HARBOR_ANTHROPIC_AUTH_TOKEN HARBOR_ANTHROPIC_CUSTOM_HEADERS HARBOR_CLAUDE_CODE_MAX_OUTPUT_TOKENS
export HARBOR_CLAUDE_CODE_DISABLE_AUTOUPDATER HARBOR_ANTHROPIC_MODEL HARBOR_ANTHROPIC_DEFAULT_OPUS_MODEL HARBOR_ANTHROPIC_DEFAULT_SONNET_MODEL HARBOR_ANTHROPIC_DEFAULT_HAIKU_MODEL HARBOR_CLAUDE_CODE_SUBAGENT_MODEL HARBOR_CLAUDE_CODE_EFFORT_LEVEL
export HARBOR_TIMEOUT_MULTIPLIER HARBOR_AGENT_TIMEOUT_MULTIPLIER HARBOR_AGENT_SETUP_TIMEOUT_MULTIPLIER HARBOR_FORCE_BUILD HARBOR_DEBUG TRACE_PLUGIN_SOURCE_DIR TRACE_PLUGIN_CLAUDE_HOOK_SOURCE TRACE_PLUGIN_OPENCODE_PLUGIN_SOURCE TRACE_PLUGIN_OPENCODE_HOOK_SOURCE HARBOR_CC_OPIK_ENABLE_HOOK
export HARBOR_CC_HOOK_SOURCE HARBOR_CC_HOOK_MOUNT_PATH HARBOR_CC_CLAUDE_TGZ_SOURCE HARBOR_CC_CLAUDE_TGZ_MOUNT_PATH
export HARBOR_CC_PY_WHEEL_DIR_SOURCE HARBOR_CC_PY_WHEEL_DIR_MOUNT_PATH HARBOR_CC_NPM_CACHE_MOUNT_PATH HARBOR_VERIFIER_UV_HOME HARBOR_VERIFIER_UV_BIN_DIR_MOUNT_PATH HARBOR_E2B_VERIFIER_UV_SOURCE HARBOR_CC_OPIK_DEBUG HARBOR_CC_OPIK_INSTALL_DEPS
export HARBOR_CC_WEB_MCP_SOURCE HARBOR_CC_WEB_MCP_MOUNT_PATH
export QZ_NODE_DIST_URL NPM_CONFIG_REGISTRY GO111MODULE GOPROXY GOSUMDB
export RUSTUP_UPDATE_ROOT RUSTUP_DIST_SERVER CARGO_REGISTRY_REPLACE_WITH CARGO_REGISTRY_URL
export PIP_INDEX_URL PIP_EXTRA_INDEX_URL PIP_TRUSTED_HOST UV_INDEX_URL UV_DEFAULT_INDEX
export HARBOR_PIP_DEFAULT_TIMEOUT HARBOR_PIP_RETRIES
export HARBOR_SKIP_DOCKERHUB_PREFLIGHT HARBOR_DOCKERHUB_CHECK_TIMEOUT HARBOR_DOCKERHUB_PREFLIGHT_STRICT SMITH_GENERATE_IF_MISSING SMITH_ADAPTER_DIR FIX_GIT_IMAGE_NAME FIX_GIT_WARM_LABEL
export OPENCODE_PROVIDER OPENCODE_VERSION OPENCODE_TGZ_BASENAME OPENCODE_LINUX_X64_TGZ_BASENAME OPENCODE_CONFIG_CONTENT OPENCODE_RUNTIME_SECRETS_JSON
export NEXT_INDEX_FILE LOCK_FILE WORKERS_READY_FILE WORKERS_FAILED_FILE
export ROLLOUT RL_UTILS_DIR RL_ENV_FILE RL_HOST RL_PORT RL_DATASET_NAME RL_DATASET_ROOT RL_DATASET_ROOTS RL_TRIALS_DIR RL_MAX_CONCURRENT
export RL_AGENT RL_MODEL_NAME RL_MODEL_PREFIX RL_API_BASE RL_API_KEY RL_API_KEY_MODE MODEL_REQUEST_CONFIG_JSON RL_DISABLED_TASK_IDS RL_ENVIRONMENT_TYPE RL_E2B_SANDBOX_TIMEOUT_SEC RL_E2B_PREBUILT_TEMPLATE RL_FORCE_BUILD
export RL_TRACE_LOG RL_SERVER_LOG RL_SERVER_PID_FILE RL_QUEUE_DIR RL_ACTIVE_DIR RL_JOB_QUEUE_ROOT RL_JOB_RUNTIME_ROOT RL_DYNAMIC_JOB_ZELLIJ RL_JOB_ZELLIJ_START_TIMEOUT RL_JOB_ZELLIJ_LOCK_TIMEOUT RL_JOB_ZELLIJ_READY_TIMEOUT RL_WORKERS RL_REQUEST_TIMEOUT RL_KEEP_TRIALS_PER_WORKER RL_MODEL_INFO RL_MAX_NEW_TOKENS RL_CLAUDE_CODE_MAX_OUTPUT_TOKENS RL_MAX_TURNS RL_AGENT_TIMEOUT_MULTIPLIER RL_LLM_TIMEOUT RL_LLM_MAX_RETRIES
export RL_TEMPERATURE RL_TOP_P RL_TOP_K RL_MIN_P RL_COLLECT_ROLLOUT_DETAILS RL_ENABLE_SUMMARIZE
export PATH="/opt/tb-venv/bin:${PATH}"

harbor_init_run_dirs() {
  mkdir -p "$OUTPUT_PATH" "$QUEUE_DIR" "$RUNTIME_DIR/worker-logs" "$JOBS_ROOT"
  touch "$QUEUE_DIR/done.txt" "$QUEUE_DIR/failed.txt"
}

harbor_agent_is_opencode() {
  [[ "$AGENT" == "opencode" ]]
}

harbor_agent_is_claude_code() {
  [[ "$AGENT" == "claude-code" ]]
}

harbor_agent_is_pi() {
  [[ "$AGENT" == "pi" ]]
}

harbor_agent_tgz_basename() {
  if harbor_agent_is_opencode; then
    printf '%s\n' "$OPENCODE_TGZ_BASENAME"
  elif harbor_agent_is_pi; then
    printf '%s\n' "$PI_RUNTIME_BASENAME"
  else
    printf '%s\n' "$CLAUDE_CODE_TGZ_BASENAME"
  fi
}

harbor_validate_generation_controls() {
  if [[ -n "$HARBOR_MAX_TOKENS" && ! "$HARBOR_MAX_TOKENS" =~ ^[1-9][0-9]*$ ]]; then
    echo "[ERROR] HARBOR_MAX_TOKENS must be a positive integer." >&2
    return 1
  fi
  if [[ "$ROLLOUT" != "1" ]] \
    && { harbor_agent_is_claude_code || harbor_agent_is_pi; } \
    && [[ -n "$HARBOR_TEMPERATURE" || -n "$HARBOR_TOP_P" ]]; then
    local agent_display="Claude Code"
    if harbor_agent_is_pi; then
      agent_display="Pi"
    fi
    echo "[ERROR] $agent_display does not expose temperature or top_p controls." >&2
    echo "[ERROR] Use AGENT=opencode for these settings, or leave them unset." >&2
    return 1
  fi
}

harbor_analyzer_pid_matches_run() {
  local pid="$1" arg previous="" script_seen=0 run_seen=0 handover_seen=0
  [[ "$pid" =~ ^[0-9]+$ && -r "/proc/$pid/cmdline" ]] || return 1
  while IFS= read -r -d '' arg; do
    [[ "$arg" == "$SCRIPT_DIR/scripts/analyzer_subagent.py" ]] && script_seen=1
    [[ "$previous" == "--run-dir" && "$arg" == "$OUTPUT_PATH" ]] && run_seen=1
    [[ "$previous" == "--handover" && "$arg" == "$HARBOR_MONITOR_DIR/analyzer-handover-latest.json" ]] && handover_seen=1
    previous="$arg"
  done < "/proc/$pid/cmdline"
  [[ "$script_seen" == 1 && "$run_seen" == 1 && "$handover_seen" == 1 ]]
}

harbor_process_start_time() {
  local pid="$1"
  [[ "$pid" =~ ^[0-9]+$ && -r "/proc/$pid/stat" ]] || return 1
  awk '{print $22}' "/proc/$pid/stat" 2>/dev/null
}

harbor_identity_file_value() {
  local file="$1" key="$2" line_key line_value
  [[ -f "$file" ]] || return 1
  while IFS='=' read -r line_key line_value; do
    if [[ "$line_key" == "$key" ]]; then
      printf '%s\n' "$line_value"
      return 0
    fi
  done < "$file"
  return 1
}

harbor_write_analyzer_supervisor_identity() {
  local pid="$1" analyzer_pid="$2" start_time analyzer_start_time
  start_time="$(harbor_process_start_time "$pid")" || return 1
  analyzer_start_time="$(harbor_process_start_time "$analyzer_pid")" || return 1
  {
    printf 'pid=%s\n' "$pid"
    printf 'start_time=%s\n' "$start_time"
    printf 'run_dir=%s\n' "$OUTPUT_PATH"
    printf 'analyzer_pid=%s\n' "$analyzer_pid"
    printf 'analyzer_start_time=%s\n' "$analyzer_start_time"
  } > "$HARBOR_ANALYZER_SUPERVISOR_ID_FILE"
}

harbor_analyzer_supervisor_pid_matches_run() {
  local pid="$1" expected_analyzer_pid="${2:-}" stored_pid start_time run_dir analyzer_pid analyzer_start_time
  local current_start_time current_analyzer_start_time
  [[ "$pid" =~ ^[0-9]+$ && -r "/proc/$pid/stat" ]] || return 1
  stored_pid="$(harbor_identity_file_value "$HARBOR_ANALYZER_SUPERVISOR_ID_FILE" pid || true)"
  start_time="$(harbor_identity_file_value "$HARBOR_ANALYZER_SUPERVISOR_ID_FILE" start_time || true)"
  run_dir="$(harbor_identity_file_value "$HARBOR_ANALYZER_SUPERVISOR_ID_FILE" run_dir || true)"
  analyzer_pid="$(harbor_identity_file_value "$HARBOR_ANALYZER_SUPERVISOR_ID_FILE" analyzer_pid || true)"
  analyzer_start_time="$(harbor_identity_file_value "$HARBOR_ANALYZER_SUPERVISOR_ID_FILE" analyzer_start_time || true)"
  [[ "$stored_pid" == "$pid" && "$run_dir" == "$OUTPUT_PATH" ]] || return 1
  current_start_time="$(harbor_process_start_time "$pid")" || return 1
  [[ -n "$start_time" && "$start_time" == "$current_start_time" ]] || return 1
  [[ -z "$expected_analyzer_pid" || "$analyzer_pid" == "$expected_analyzer_pid" ]] || return 1
  if [[ -n "$expected_analyzer_pid" ]]; then
    [[ "$analyzer_pid" =~ ^[0-9]+$ && -r "/proc/$analyzer_pid/stat" ]] || return 1
    current_analyzer_start_time="$(harbor_process_start_time "$analyzer_pid")" || return 1
    [[ -n "$analyzer_start_time" && "$analyzer_start_time" == "$current_analyzer_start_time" ]] || return 1
    harbor_analyzer_pid_matches_run "$analyzer_pid"
  fi
}

harbor_agent_is_oracle() {
  [[ "$AGENT" == "oracle" ]]
}

harbor_validate_agent() {
  case "$AGENT" in
    claude-code|opencode|pi|oracle) ;;
    *)
      echo "[ERROR] AGENT must be claude-code, opencode, pi, or oracle, got: $AGENT" >&2
      exit 1
      ;;
  esac

  if harbor_agent_is_opencode; then
    if [[ -z "$OPENCODE_CONFIG_CONTENT" ]]; then
      echo "[WARN] AGENT=opencode but OPENCODE_CONFIG_CONTENT is empty;" >&2
      echo "[WARN] opencode will fall back to ANTHROPIC_* env if provided." >&2
    fi
  fi
  if harbor_agent_is_pi; then
    case "$PI_THINKING_LEVEL" in
      off|minimal|low|medium|high|xhigh|max) ;;
      *)
        echo "[ERROR] PI_THINKING_LEVEL must be off, minimal, low, medium, high, xhigh, or max." >&2
        exit 1
        ;;
    esac
  fi
}

harbor_monitor_pid_matches_run() {
  local pid="$1" arg previous="" script_seen=0 run_seen=0
  [[ "$pid" =~ ^[0-9]+$ && -r "/proc/$pid/cmdline" ]] || return 1
  while IFS= read -r -d '' arg; do
    [[ "$arg" == "$SCRIPT_DIR/scripts/monitor.py" ]] && script_seen=1
    [[ "$previous" == "--run-dir" && "$arg" == "$OUTPUT_PATH" ]] && run_seen=1
    previous="$arg"
  done < "/proc/$pid/cmdline"
  [[ "$script_seen" == 1 && "$run_seen" == 1 ]]
}

harbor_online_analysis_pid_matches_run() {
  local pid="$1" arg script_seen=0 run_seen=0
  [[ "$pid" =~ ^[0-9]+$ && -r "/proc/$pid/cmdline" ]] || return 1
  while IFS= read -r -d '' arg; do
    [[ "$arg" == "$SCRIPT_DIR/scripts/online_rule_analyzer.py" ]] && script_seen=1
    [[ "$arg" == "$OUTPUT_PATH" ]] && run_seen=1
  done < "/proc/$pid/cmdline"
  [[ "$script_seen" == 1 && "$run_seen" == 1 ]]
}

# Call only after the subsystem-specific PID identity check succeeds.
harbor_terminate_validated_process() {
  local pid="$1" wait_attempts="${2:-30}" sid signal_target attempt
  sid="$(ps -o sid= -p "$pid" 2>/dev/null | tr -d ' ' || true)"
  signal_target="$pid"
  [[ "$sid" == "$pid" ]] && signal_target="-$pid"
  kill -TERM -- "$signal_target" >/dev/null 2>&1 || true
  for attempt in $(seq 1 "$wait_attempts"); do
    kill -0 "$pid" >/dev/null 2>&1 || break
    sleep 1
  done
  if kill -0 "$pid" >/dev/null 2>&1; then
    kill -KILL -- "$signal_target" >/dev/null 2>&1 || true
  fi
}

harbor_stop_online_analysis() {
  [[ -f "$HARBOR_ONLINE_ANALYSIS_PID_FILE" ]] || return 0
  local pid
  pid="$(cat "$HARBOR_ONLINE_ANALYSIS_PID_FILE" 2>/dev/null || true)"
  if [[ ! "$pid" =~ ^[0-9]+$ ]] || ! kill -0 "$pid" >/dev/null 2>&1; then
    rm -f "$HARBOR_ONLINE_ANALYSIS_PID_FILE"
    return 0
  fi
  if ! harbor_online_analysis_pid_matches_run "$pid"; then
    echo "[ERROR] refusing to stop unrelated process from $HARBOR_ONLINE_ANALYSIS_PID_FILE: pid=$pid" >&2
    return 1
  fi
  harbor_terminate_validated_process "$pid"
  rm -f "$HARBOR_ONLINE_ANALYSIS_PID_FILE"
}

harbor_stop_monitor() {
  [[ -f "$HARBOR_MONITOR_PID_FILE" ]] || return 0
  local pid
  pid="$(cat "$HARBOR_MONITOR_PID_FILE" 2>/dev/null || true)"
  if [[ ! "$pid" =~ ^[0-9]+$ ]] || ! kill -0 "$pid" >/dev/null 2>&1; then
    rm -f "$HARBOR_MONITOR_PID_FILE"
    return 0
  fi
  if ! harbor_monitor_pid_matches_run "$pid"; then
    echo "[ERROR] refusing to stop unrelated process from $HARBOR_MONITOR_PID_FILE: pid=$pid" >&2
    return 1
  fi
  harbor_terminate_validated_process "$pid"
  rm -f "$HARBOR_MONITOR_PID_FILE"
}

harbor_reset_run_state() (
  mkdir -p "$OUTPUT_PATH/fixer"
  exec 8>>"$OUTPUT_PATH/fixer/.fixer-control.lock"
  flock -x 8
  if ! python3 "$SCRIPT_DIR/scripts/controller.py" --run-dir "$OUTPUT_PATH" fixer reset-control --lock-fd 8 >/dev/null; then
    echo "[ERROR] refusing to reset run state while Fixer is active" >&2
    return 1
  fi
  harbor_stop_analyzer_supervisor
  harbor_stop_analyzer
  harbor_stop_monitor
  harbor_stop_online_analysis
  rm -f "$QUEUE_DIR"/worker-*.current "$LOCK_FILE" "$WORKERS_READY_FILE" "$WORKERS_FAILED_FILE"
  rm -f "$NEXT_INDEX_FILE"
  rm -f "$OUTPUT_PATH/.monitor_state.json" "$HARBOR_MONITOR_LOG_FILE" "$HARBOR_BENCHMARK_PID_FILE" "$HARBOR_BENCHMARK_EXIT_FILE" "$HARBOR_JOB_DIR_FILE"
  rm -rf "$HARBOR_MONITOR_DIR"
  rm -f "$HARBOR_ANALYZER_PID_FILE" "$HARBOR_ANALYZER_SUPERVISOR_PID_FILE" "$HARBOR_ANALYZER_SUPERVISOR_ID_FILE" "$HARBOR_ANALYZER_LOG_FILE" "$HARBOR_ANALYZER_OUTPUT_DIR/.analyzer_state.json" "$HARBOR_ANALYZER_OUTPUT_DIR/.analyzer-ready" "$HARBOR_ANALYZER_OUTPUT_DIR/analyzer-artifacts-latest.json" "$HARBOR_ANALYZER_OUTPUT_DIR/benchmark-summary.md"
  rm -rf "$HARBOR_ANALYZER_OUTPUT_DIR/benchmark-summary"
  rm -f "$OUTPUT_PATH/fixer/fix-report-latest.md"
  rm -f "$HARBOR_ONLINE_ANALYSIS_PID_FILE" "$HARBOR_ONLINE_ANALYSIS_LOG_FILE"
  rm -f "$HARBOR_ONLINE_ANALYSIS_DIR/environment-events.jsonl" "$HARBOR_ONLINE_ANALYSIS_DIR/environment-summary.json"
  : > "$QUEUE_DIR/done.txt"
  : > "$QUEUE_DIR/failed.txt"
)

harbor_stop_analyzer_supervisor() {
  [[ -f "$HARBOR_ANALYZER_SUPERVISOR_PID_FILE" ]] || return 0
  local pid
  pid="$(cat "$HARBOR_ANALYZER_SUPERVISOR_PID_FILE" 2>/dev/null || true)"
  if [[ ! "$pid" =~ ^[0-9]+$ ]] || ! kill -0 "$pid" >/dev/null 2>&1; then
    rm -f "$HARBOR_ANALYZER_SUPERVISOR_PID_FILE" "$HARBOR_ANALYZER_SUPERVISOR_ID_FILE"
    return 0
  fi
  if ! harbor_analyzer_supervisor_pid_matches_run "$pid"; then
    echo "[ERROR] refusing to stop unrelated process from $HARBOR_ANALYZER_SUPERVISOR_PID_FILE: pid=$pid" >&2
    return 1
  fi
  kill -TERM "$pid" >/dev/null 2>&1 || true
  for _ in $(seq 1 10); do
    kill -0 "$pid" >/dev/null 2>&1 || break
    sleep 1
  done
  if kill -0 "$pid" >/dev/null 2>&1; then
    kill -KILL "$pid" >/dev/null 2>&1 || true
  fi
  rm -f "$HARBOR_ANALYZER_SUPERVISOR_PID_FILE" "$HARBOR_ANALYZER_SUPERVISOR_ID_FILE"
}

harbor_stop_analyzer() {
  [[ -f "$HARBOR_ANALYZER_PID_FILE" ]] || return 0
  local expected_pid="${1:-}" current_pid pid
  current_pid="$(cat "$HARBOR_ANALYZER_PID_FILE" 2>/dev/null || true)"
  pid="${expected_pid:-$current_pid}"
  if [[ -n "$expected_pid" && "$current_pid" != "$expected_pid" ]]; then
    [[ "$expected_pid" =~ ^[0-9]+$ ]] || return 0
  fi
  if [[ ! "$pid" =~ ^[0-9]+$ ]] || ! kill -0 "$pid" >/dev/null 2>&1; then
    [[ -z "$expected_pid" || "$current_pid" == "$expected_pid" ]] && rm -f "$HARBOR_ANALYZER_PID_FILE"
    return 0
  fi
  if ! harbor_analyzer_pid_matches_run "$pid"; then
    echo "[ERROR] refusing to stop unrelated process from $HARBOR_ANALYZER_PID_FILE: pid=$pid" >&2
    return 1
  fi
  harbor_terminate_validated_process "$pid"
  [[ -z "$expected_pid" || "$current_pid" == "$expected_pid" ]] && rm -f "$HARBOR_ANALYZER_PID_FILE"
}

harbor_generate_task_file() {
  local destination="${1:-$TASK_FILE}" source_file=""
  # Explicit local paths must be validated against the checkout the user
  # selected, not a similarly named repository manifest.
  if [[ -n "$TASK_SOURCE_FILE" || -z "$FLEET_TASKS" || "$DATASET_NAME" != "auto" ]]; then
    source_file="$(harbor_task_source_file || true)"
  fi
  if [[ -n "$source_file" ]]; then
    cp "$source_file" "$destination"
    return 0
  fi

  if [[ ! -d "$DATASET_PATH" ]]; then
    echo "DATASET_PATH not found: $DATASET_PATH" >&2
    return 1
  fi

  # Harbor local datasets are one task per top-level directory.  SWE-smith uses
  # instruction.md, while SETA/Terminal-Bench tasks use task.yaml.  Keep this
  # scan format-neutral so the same zellij runner can handle both datasets.
  python3 "$SCRIPT_DIR/env.py" generate-task-file "$DATASET_PATH" "$destination"
}

harbor_filter_task_file() {
  local source_file="$1" destination="$2"
  python3 "$SCRIPT_DIR/env.py" filter-task-file "$source_file" "$destination" "$FLEET_TASKS"
}

harbor_validate_local_task_selection() {
  [[ -n "$FLEET_TASKS" ]] || return 0
  local all_tasks selected_tasks
  all_tasks="$(mktemp "${TMPDIR:-/tmp}/harbor-all-tasks.XXXXXX")"
  selected_tasks="$(mktemp "${TMPDIR:-/tmp}/harbor-selected-tasks.XXXXXX")"
  if ! harbor_generate_task_file "$all_tasks" ||
     ! harbor_filter_task_file "$all_tasks" "$selected_tasks"; then
    rm -f "$all_tasks" "$selected_tasks"
    return 2
  fi
  rm -f "$all_tasks" "$selected_tasks"
}

harbor_dataset_name_is_registry_id() {
  local name="$1"
  [[ "$name" == */* || "$name" == *@* ]]
}

harbor_dataset_kind() {
  if [[ "$DATASET_NAME" != "auto" ]]; then
    if harbor_dataset_name_is_registry_id "$DATASET_NAME"; then
      printf 'harbor\n'
      return 0
    fi
    printf '%s\n' "$DATASET_NAME"
    return 0
  fi
  case "$DATASET_PATH" in
    */seta-env|*/seta-env/Dataset|*seta*) printf 'seta\n' ;;
    *swesmith*|*smith*) printf 'smith\n' ;;
    *terminal-bench-2-1*|*terminalbench21*|*terminal-bench21*) printf 'terminalbench21\n' ;;
    *swebench-verified*|*sweverify*|*swe-verify*) printf 'sweverify\n' ;;
    *) printf 'harbor\n' ;;
  esac
}

harbor_builtin_task_file() {
  case "$(harbor_dataset_kind)" in
    seta) printf '%s\n' "$TASKS_DIR/SETA/harbor_tasks.txt" ;;
    smith) printf '%s\n' "$TASKS_DIR/SWE-smith/harbor_tasks.txt" ;;
    terminalbench21) printf '%s\n' "$TASKS_DIR/Terminal-bench-2/harbor_terminalbench21_tasks.txt" ;;
    sweverify) printf '%s\n' "$TASKS_DIR/SWE-verify/harbor_tasks.txt" ;;
    *) return 1 ;;
  esac
}

harbor_task_source_file() {
  if [[ -n "${TASK_SOURCE_FILE:-}" ]]; then
    if [[ ! -s "$TASK_SOURCE_FILE" ]]; then
      echo "TASK_SOURCE_FILE not found or empty: $TASK_SOURCE_FILE" >&2
      return 1
    fi
    printf '%s\n' "$TASK_SOURCE_FILE"
    return 0
  fi

  local builtin
  builtin="$(harbor_builtin_task_file || true)"
  if [[ -n "$builtin" && -s "$builtin" ]]; then
    printf '%s\n' "$builtin"
    return 0
  fi

  if [[ -n "$builtin" ]]; then
    echo "[WARN] built-in task list missing or empty: $builtin; falling back to DATASET_PATH scan" >&2
  fi
  return 1
}

harbor_metric_mode() {
  if [[ "$METRIC_MODE" != "auto" ]]; then
    printf '%s\n' "$METRIC_MODE"
    return 0
  fi
  if [[ "$(harbor_dataset_kind)" == "seta" || "$(harbor_dataset_kind)" == "terminalbench21" || "$(harbor_dataset_kind)" == "sweverify" ]]; then
    printf 'success\n'
  else
    printf 'reward\n'
  fi
}

harbor_registry_dataset_name() {
  case "$DATASET_NAME" in
    seta) printf 'seta-env\n'; return 0 ;;
    terminalbench21) printf '%s\n' "$HARBOR_TERMINALBENCH21_REGISTRY_ID"; return 0 ;;
    sweverify) printf 'swebench-verified\n'; return 0 ;;
  esac
  if harbor_dataset_name_is_registry_id "$DATASET_NAME"; then
    printf '%s\n' "$DATASET_NAME"
    return 0
  fi
  return 1
}

harbor_metadata_dataset_name() {
  if harbor_uses_registry_dataset; then
    harbor_registry_dataset_name
  else
    harbor_dataset_kind
  fi
}

harbor_uses_registry_dataset() {
  harbor_registry_dataset_name >/dev/null
}

harbor_registry_task_name() {
  local task_name="$1"
  if [[ "$(harbor_registry_dataset_name 2>/dev/null || true)" == "$HARBOR_TERMINALBENCH21_REGISTRY_ID" ]] \
    && [[ "$task_name" != */* ]]; then
    printf 'terminal-bench/%s\n' "$task_name"
    return 0
  fi
  printf '%s\n' "$task_name"
}

harbor_prepare_registry_task_selection() {
  [[ -n "$FLEET_TASKS" ]] || return 0
  local source_file selected_tasks
  source_file="$(harbor_task_source_file || true)"
  if [[ -z "$source_file" || ! -s "$source_file" ]]; then
    printf '[ERROR] --task is unsupported for Harbor registry taskset: %s\n' "$DATASET_NAME" >&2
    return 2
  fi
  selected_tasks="$(mktemp "${TMPDIR:-/tmp}/harbor-selected-tasks.XXXXXX")"
  if ! harbor_filter_task_file "$source_file" "$selected_tasks"; then
    rm -f "$selected_tasks"
    return 2
  fi
  rm -f "$selected_tasks"
  INCLUDE_TASKS="$FLEET_TASKS"
  HARBOR_INCLUDE_TASKS="$FLEET_TASKS"
  export INCLUDE_TASKS HARBOR_INCLUDE_TASKS
}

harbor_validate_task_selection() {
  [[ -n "$FLEET_TASKS" ]] || return 0
  if [[ "$ROLLOUT" == "1" ]]; then
    printf '[ERROR] --task is unsupported when ROLLOUT=1\n' >&2
    return 2
  fi
  if harbor_uses_registry_dataset; then
    harbor_prepare_registry_task_selection
  else
    harbor_validate_local_task_selection
  fi
}

harbor_prepare_task_file() {
  mkdir -p "$(dirname "$TASK_FILE")"
  (
  flock -x 9
  if [[ -z "$FLEET_TASKS" ]]; then
    if [[ "${RESET_RUN:-0}" == "1" || ! -s "$TASK_FILE" ]]; then
      harbor_generate_task_file
    fi
  else
    local all_tasks selected_tasks
    all_tasks="$(mktemp "$(dirname "$TASK_FILE")/.all-tasks.XXXXXX")"
    selected_tasks="$(mktemp "$(dirname "$TASK_FILE")/.selected-tasks.XXXXXX")"
    if ! harbor_generate_task_file "$all_tasks" ||
       ! harbor_filter_task_file "$all_tasks" "$selected_tasks"; then
      rm -f "$all_tasks" "$selected_tasks"
      return 2
    fi
    rm -f "$all_tasks"

    if [[ "${RESET_RUN:-0}" != "1" && -s "$TASK_FILE" ]]; then
      if ! cmp -s "$TASK_FILE" "$selected_tasks"; then
        rm -f "$selected_tasks"
        printf '[ERROR] task selection does not match existing task file: %s\n' "$TASK_FILE" >&2
        printf '[ERROR] set RESET_RUN=1 or use a new RUN_ID\n' >&2
        return 2
      fi
      rm -f "$selected_tasks"
    else
      mv -f "$selected_tasks" "$TASK_FILE"
    fi
  fi
  if [[ ! -f "$NEXT_INDEX_FILE" ]]; then
    echo 1 > "$NEXT_INDEX_FILE"
  fi
  ) 9>"${TASK_FILE}.lock"
}

harbor_task_count() {
  if [[ -f "$TASK_FILE" ]]; then
    wc -l < "$TASK_FILE" | tr -d ' '
  else
    echo 0
  fi
}

harbor_ensure_dataset() {
  local dataset_kind
  dataset_kind="$(harbor_dataset_kind)"

  if harbor_uses_registry_dataset; then
    harbor_registry_dataset_name >/dev/null
    return 0
  fi

  if [[ -d "$DATASET_PATH" ]] && [[ -n "$(find -L "$DATASET_PATH" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | head -n 1)" ]]; then
    return 0
  fi

  if [[ "$dataset_kind" == "smith" && "$SMITH_GENERATE_IF_MISSING" == "1" ]]; then
    if [[ ! -d "$SMITH_ADAPTER_DIR" ]]; then
      echo "smith dataset missing and adapter not found: $SMITH_ADAPTER_DIR" >&2
      return 1
    fi
    echo "[INFO] smith dataset not found at $DATASET_PATH, generating with $SMITH_ADAPTER_DIR"
    (
      cd "$SMITH_ADAPTER_DIR"
      uv sync
      uv run run_adapter.py --limit 0
    )
  fi

  if [[ ! -d "$DATASET_PATH" ]]; then
    echo "DATASET_PATH not found: $DATASET_PATH" >&2
    if [[ "$dataset_kind" == "harbor" ]]; then
      echo "automatic TerminalBench dataset cloning was removed" >&2
      printf '%s\n' \
        "set DATASET_PATH to an existing local Harbor dataset" \
        "or select a registry DATASET_NAME" >&2
    fi
    return 1
  fi
}

harbor_pick_task() {
  exec 9>"$LOCK_FILE"
  flock 9

  local total idx task_name
  total="$(harbor_task_count)"
  idx="$(cat "$NEXT_INDEX_FILE" 2>/dev/null || echo 1)"
  if [[ -z "$idx" || "$idx" -gt "$total" ]]; then
    flock -u 9
    return 1
  fi

  task_name="$(sed -n "${idx}p" "$TASK_FILE" | tr -d '\r')"
  echo $((idx + 1)) > "$NEXT_INDEX_FILE"
  flock -u 9

  [[ -n "$task_name" ]] || return 1
  printf '%s\t%s\n' "$idx" "$task_name"
}

harbor_wait_for_workers_ready() {
  while true; do
    if [[ -f "$WORKERS_READY_FILE" ]]; then
      harbor_apply_effective_wheel_source
      return 0
    fi
    [[ -f "$WORKERS_FAILED_FILE" ]] && return 1
    sleep 1
  done
}

harbor_ensure_local_wheels_server() {
  mkdir -p "$RUNTIME_DIR"
  local pid_file="${RUNTIME_DIR}/local-wheel-http.pid"
  local log_file="${RUNTIME_DIR}/local-wheel-http.log"
  local port pid attempt last_port

  [[ -d "$LOCAL_WHEEL_DIR" ]] || return 0

  last_port=$((LOCAL_WHEEL_PORT + LOCAL_WHEEL_PORT_ATTEMPTS - 1))
  for port in $(seq "$LOCAL_WHEEL_PORT" "$last_port"); do
    export HARBOR_LOCAL_WHEEL_SERVER_URL="http://${LOCAL_WHEEL_HOST_IP}:${port}"
    export HARBOR_LOCAL_CLAUDE_TGZ_URL="${HARBOR_LOCAL_WHEEL_SERVER_URL%/}/${CLAUDE_CODE_TGZ_BASENAME}"
    local agent_tgz
    agent_tgz="$(harbor_agent_tgz_basename)"

    # Treat wheel servers without the selected agent tgz as incomplete.
    local urls=("${HARBOR_LOCAL_WHEEL_SERVER_URL%/}/manifest.txt" "${HARBOR_LOCAL_WHEEL_SERVER_URL%/}/${agent_tgz}")
    if harbor_agent_is_opencode; then
      urls+=("${HARBOR_LOCAL_WHEEL_SERVER_URL%/}/${OPENCODE_LINUX_X64_TGZ_BASENAME}")
    elif harbor_agent_is_pi; then
      urls+=("${HARBOR_LOCAL_WHEEL_SERVER_URL%/}/${PI_NODE_RUNTIME_BASENAME}")
    else
      urls+=("${HARBOR_LOCAL_WHEEL_SERVER_URL%/}/npm-cache-ready")
    fi

    # Avoid probing a broad range of ports. Start on the preferred port first;
    # only if binding fails do a narrow readiness check to see whether another
    # monitor already owns a compatible wheel server on that exact port.
    nohup python3 -m http.server "$port" --directory "$LOCAL_WHEEL_DIR" \
      >"$log_file.${port}" 2>&1 &
    pid="$!"
    sleep 1

    local ready=1
    local url
    if ! kill -0 "$pid" >/dev/null 2>&1; then
      ready=1
      for url in "${urls[@]}"; do
        if ! harbor_url_is_reachable "$url"; then
          ready=0
          break
        fi
      done
      if [[ "$ready" == "1" ]]; then
        echo "$port" > "${RUNTIME_DIR}/local-wheel-http.port"
        return 0
      fi
      continue
    fi

    for url in "${urls[@]}"; do
      if ! harbor_url_is_reachable "$url"; then
        ready=0
        break
      fi
    done
    if [[ "$ready" == "1" ]]; then
      echo "$pid" > "$pid_file"
      echo "$port" > "${RUNTIME_DIR}/local-wheel-http.port"
      return 0
    fi
    kill "$pid" >/dev/null 2>&1 || true
  done

  echo "failed to start a matching local wheel HTTP server in ${LOCAL_WHEEL_PORT_ATTEMPTS} attempts" >&2
  return 1
}

harbor_url_is_reachable() {
  local url="$1"
  python3 "$SCRIPT_DIR/env.py" url-reachable "$url"
}

harbor_manifest_url_ready() {
  local url="$1"
  python3 "$SCRIPT_DIR/env.py" manifest-url-ready "$url"
}

harbor_gzip_file_ready() {
  local path="$1"
  [[ -f "$path" ]] && gzip -t "$path" >/dev/null 2>&1
}

harbor_tar_file_ready() {
  local path="$1"
  python3 "$SCRIPT_DIR/env.py" tar-file-ready "$path" >/dev/null 2>&1
}

harbor_npm_tarball_version_ready() {
  local path="$1" expected_version="$2"
  python3 "$SCRIPT_DIR/env.py" npm-tarball-version-ready \
    "$path" "$expected_version" >/dev/null 2>&1
}

harbor_verifier_bundle_archive_ready() {
  local path="$1"
  [[ -f "$path" && -f "$VERIFIER_RUNTIME_BUNDLE_PREPARER" ]] \
    && python3 "$VERIFIER_RUNTIME_BUNDLE_PREPARER" \
      check --archive "$path" >/dev/null 2>&1
}

harbor_python_runtime_archive_ready() {
  local path="$1"
  [[ -f "$path" ]] \
    && python3 "$SCRIPT_DIR/python_runtime.py" \
      --check "$path" >/dev/null 2>&1
}

verifier_runtime_bundle_ready() {
  verifier_runtime_bundle_required \
    && harbor_verifier_bundle_archive_ready "$VERIFIER_RUNTIME_BUNDLE_ARCHIVE_SOURCE"
}

harbor_local_cache_ready() {
  [[ -f "$LOCAL_WHEEL_DIR/manifest.txt" ]] \
    && grep -qx 'cache_schema=3' "$LOCAL_WHEEL_DIR/manifest.txt" \
    && [[ "$(find "$LOCAL_WHEEL_DIR" -maxdepth 1 -name 'opik-*.whl' -type f | wc -l | tr -d ' ')" == "1" ]] \
    && [[ -f "$LOCAL_WHEEL_DIR/get-pip.py" ]] \
    && harbor_tar_file_ready "$LOCAL_WHEEL_DIR/node-runtime.tar.xz" \
    && harbor_python_runtime_archive_ready "$LOCAL_WHEEL_DIR/python3.12-runtime.tar.gz" \
    && {
      if harbor_agent_is_opencode; then
        harbor_gzip_file_ready "$LOCAL_WHEEL_DIR/${OPENCODE_TGZ_BASENAME}" \
          && harbor_gzip_file_ready "$LOCAL_WHEEL_DIR/${OPENCODE_LINUX_X64_TGZ_BASENAME}"
      elif harbor_agent_is_pi; then
        harbor_gzip_file_ready "$LOCAL_WHEEL_DIR/${PI_TGZ_BASENAME}" \
          && harbor_tar_file_ready "$LOCAL_WHEEL_DIR/${PI_NODE_RUNTIME_BASENAME}" \
          && harbor_tar_file_ready "$LOCAL_WHEEL_DIR/${PI_RUNTIME_BASENAME}" \
          && grep -qx "pi_runtime_version=${PI_VERSION}" "$LOCAL_WHEEL_DIR/manifest.txt"
      else
        harbor_npm_tarball_version_ready \
          "$LOCAL_WHEEL_DIR/${CLAUDE_CODE_TGZ_BASENAME}" \
          "$CLAUDE_CODE_VERSION" \
          && [[ -d "$LOCAL_WHEEL_DIR/npm-cache/_cacache" ]] \
          && grep -qx "$CLAUDE_CODE_VERSION" "$LOCAL_WHEEL_DIR/npm-cache-ready" \
          && grep -qx "claude_npm_cache_version=${CLAUDE_CODE_VERSION}" "$LOCAL_WHEEL_DIR/manifest.txt"
      fi
    }
}

harbor_pick_remote_wheel_url() {
  # Pi unpacks its pinned runtime from the read-only dependency mount. A
  # remote URL cannot materialize that mount, so Pi always prepares locally.
  if harbor_agent_is_pi; then
    return 1
  fi
  # Claude's npm package has platform-specific optional dependencies. The
  # remote cache path exposes only the top-level tarball to Docker trials, not
  # the accompanying npm cache, so it can silently fall back to an online npm
  # install in every task container. Prepare a complete local cache instead so
  # the tarball and npm cache are mounted together.
  if harbor_agent_is_claude_code \
    && [[ "$HARBOR_ENVIRONMENT_TYPE" == "docker" ]]; then
    return 1
  fi
  local candidates=()
  local candidate
  if [[ -n "${HARBOR_REMOTE_WHEEL_SERVER_URLS:-}" ]]; then
    IFS=',' read -r -a candidates <<< "$HARBOR_REMOTE_WHEEL_SERVER_URLS"
  elif [[ -n "${HARBOR_LOCAL_WHEEL_SERVER_URL:-}" ]]; then
    candidates=("$HARBOR_LOCAL_WHEEL_SERVER_URL")
  fi

  for candidate in "${candidates[@]}"; do
    candidate="${candidate%% }"
    candidate="${candidate## }"
    [[ -n "${candidate:-}" ]] || continue
    local agent_tgz
    agent_tgz="$(harbor_agent_tgz_basename)"
    local urls=("${candidate%/}/${agent_tgz}")
    if harbor_agent_is_opencode; then
      urls+=("${candidate%/}/${OPENCODE_LINUX_X64_TGZ_BASENAME}")
    else
      urls+=("${candidate%/}/npm-cache-ready")
    fi
    local ready=1
    local url
    local manifest_requirement=""
    if harbor_agent_is_pi; then
      manifest_requirement="pi_runtime_version=${PI_VERSION}"
    fi
    if ! harbor_manifest_url_ready "${candidate%/}/manifest.txt" "$manifest_requirement"; then
      ready=0
    fi
    for url in "${urls[@]}"; do
      if ! harbor_url_is_reachable "$url"; then
        ready=0
        break
      fi
    done
    if [[ "$ready" == "1" ]]; then
      printf '%s\n' "${candidate%/}"
      return 0
    fi
  done
  return 1
}

harbor_write_effective_wheel_source() {
  local wheel_url="$1"
  printf '%s\n' "$wheel_url" > "$EFFECTIVE_WHEEL_URL_FILE"
  printf '%s\n' "${wheel_url%/}/${CLAUDE_CODE_TGZ_BASENAME}" > "$EFFECTIVE_CLAUDE_TGZ_URL_FILE"
  export HARBOR_LOCAL_WHEEL_SERVER_URL="$wheel_url"
  export HARBOR_LOCAL_CLAUDE_TGZ_URL="${wheel_url%/}/${CLAUDE_CODE_TGZ_BASENAME}"
}

harbor_apply_effective_wheel_source() {
  if [[ "$HARBOR_ENVIRONMENT_TYPE" == "e2b" \
    || "$HARBOR_ENVIRONMENT_TYPE" == "qz" \
    || "$HARBOR_ENVIRONMENT_TYPE" == "opensandbox" ]]; then
    # Managed Sandboxes do not provide Notebook-host bind mounts. Avoid making
    # their setup depend on inbound reachability to an ephemeral runner HTTP
    # server; use the configured Sandbox-side registry/dist source instead.
    unset HARBOR_LOCAL_WHEEL_SERVER_URL HARBOR_LOCAL_CLAUDE_TGZ_URL
    return 0
  fi
  if [[ -f "$EFFECTIVE_WHEEL_URL_FILE" ]]; then
    export HARBOR_LOCAL_WHEEL_SERVER_URL="$(cat "$EFFECTIVE_WHEEL_URL_FILE")"
  fi
  if [[ -f "$EFFECTIVE_CLAUDE_TGZ_URL_FILE" ]]; then
    export HARBOR_LOCAL_CLAUDE_TGZ_URL="$(cat "$EFFECTIVE_CLAUDE_TGZ_URL_FILE")"
  elif [[ -n "${HARBOR_LOCAL_WHEEL_SERVER_URL:-}" ]]; then
    export HARBOR_LOCAL_CLAUDE_TGZ_URL="${HARBOR_LOCAL_WHEEL_SERVER_URL%/}/${CLAUDE_CODE_TGZ_BASENAME}"
  fi
}

harbor_prewarm_s3_upload_sources() {
  local -a sources=("$@")
  echo "prewarming immutable OpenSandbox S3 objects..."
  if python3 "$SCRIPT_DIR/opensandbox_s3_upload.py" preflight \
    && python3 "$SCRIPT_DIR/opensandbox_s3_upload.py" prewarm "${sources[@]}"; then
    return 0
  fi
  if [[ "$YICLOUD_SANDBOX_UPLOAD_BACKEND" == "auto" ]]; then
    echo '[WARN] OpenSandbox S3 attempt failed backend=auto phase=prewarm; runtime will retry S3 and warn before any HTTP fallback' >&2
    return 0
  fi
  return 1
}

harbor_prewarm_s3_upload_cache() {
  if [[ "$HARBOR_ENVIRONMENT_TYPE" != "opensandbox" \
    || ( "$YICLOUD_SANDBOX_UPLOAD_BACKEND" != "s3" \
      && "$YICLOUD_SANDBOX_UPLOAD_BACKEND" != "auto" ) ]]; then
    return 0
  fi
  if [[ ! -d "$LOCAL_WHEEL_DIR" ]]; then
    echo "S3 upload requires a prepared local dependency cache: $LOCAL_WHEEL_DIR" >&2
    return 1
  fi

  local -a sources=("$LOCAL_WHEEL_DIR")
  case "$AGENT" in
    claude-code)
      [[ -f "$HARBOR_CC_CLAUDE_TGZ_SOURCE" ]] \
        && sources+=("$HARBOR_CC_CLAUDE_TGZ_SOURCE")
      [[ -f "$HARBOR_CC_HOOK_SOURCE" ]] && sources+=("$HARBOR_CC_HOOK_SOURCE")
      [[ -f "$HARBOR_CC_WEB_MCP_SOURCE" ]] && sources+=("$HARBOR_CC_WEB_MCP_SOURCE")
      ;;
    opencode)
      [[ -f "$TRACE_PLUGIN_OPENCODE_PLUGIN_SOURCE" ]] \
        && sources+=("$TRACE_PLUGIN_OPENCODE_PLUGIN_SOURCE")
      [[ -f "$TRACE_PLUGIN_OPENCODE_HOOK_SOURCE" ]] \
        && sources+=("$TRACE_PLUGIN_OPENCODE_HOOK_SOURCE")
      ;;
  esac
  if verifier_runtime_bundle_required && verifier_runtime_bundle_ready; then
    sources+=("$VERIFIER_RUNTIME_BUNDLE_ARCHIVE_SOURCE")
  fi
  harbor_prewarm_s3_upload_sources "${sources[@]}"
}

harbor_build_verifier_runtime_bundle() {
  verifier_runtime_bundle_required || return 0
  validate_verifier_runtime_bundle_transport || return 1
  verifier_runtime_bundle_ready && return 0

  echo "preparing verifier runtime bundle: $VERIFIER_RUNTIME_BUNDLE_ID"
  if [[ ! -f "$VERIFIER_RUNTIME_BUNDLE_PREPARER" ]] \
    || [[ ! -x "$HARBOR_OPIK_PYTHON" ]] \
    || ! PYTHON_BIN="$HARBOR_OPIK_PYTHON" \
      "$HARBOR_OPIK_PYTHON" "$VERIFIER_RUNTIME_BUNDLE_PREPARER" build \
    --cache-dir "$HARBOR_CC_PY_WHEEL_DIR_SOURCE" \
    --output "$VERIFIER_RUNTIME_BUNDLE_ARCHIVE_SOURCE"; then
    echo "failed to prepare verifier runtime bundle: $VERIFIER_RUNTIME_BUNDLE_ID" >&2
    return 1
  fi
  if ! verifier_runtime_bundle_ready; then
    echo "prepared verifier runtime bundle is invalid: $VERIFIER_RUNTIME_BUNDLE_ARCHIVE_SOURCE" >&2
    return 1
  fi
}

harbor_prepare_verifier_runtime_bundle() {
  harbor_build_verifier_runtime_bundle || return 1
  verifier_runtime_bundle_required || return 0
  harbor_prewarm_s3_upload_sources "$VERIFIER_RUNTIME_BUNDLE_ARCHIVE_SOURCE"
}

harbor_prepare_or_select_wheels() {
  validate_verifier_runtime_bundle_transport || return 1
  mkdir -p "$RUNTIME_DIR"
  local status_file="${RUNTIME_DIR}/local-deps-prepare.status"
  rm -f "$WORKERS_READY_FILE" "$WORKERS_FAILED_FILE" "$EFFECTIVE_WHEEL_URL_FILE" "$EFFECTIVE_CLAUDE_TGZ_URL_FILE" "$HARBOR_RUNNER_PREPARE_STATUS_FILE"
  : > "$LOCAL_DEPS_LOG_FILE"
  echo "checking" > "$status_file"

  if harbor_local_cache_ready; then
    echo "using local wheel cache"
    harbor_build_verifier_runtime_bundle || {
      echo "failed" > "$status_file"
      touch "$WORKERS_FAILED_FILE"
      return 1
    }
    harbor_ensure_local_wheels_server
    harbor_write_effective_wheel_source "$HARBOR_LOCAL_WHEEL_SERVER_URL"
    harbor_prewarm_s3_upload_cache || {
      echo "failed" > "$status_file"
      touch "$WORKERS_FAILED_FILE"
      return 1
    }
    echo "done" > "$status_file"
    harbor_mark_workers_ready
    return $?
  fi

  local remote_url
  remote_url="$(harbor_pick_remote_wheel_url || true)"
  if [[ -n "${remote_url:-}" ]]; then
    if [[ "$HARBOR_ENVIRONMENT_TYPE" == "opensandbox" \
      && ( "$YICLOUD_SANDBOX_UPLOAD_BACKEND" == "s3" \
        || "$YICLOUD_SANDBOX_UPLOAD_BACKEND" == "auto" ) ]]; then
      echo "S3 upload cannot use a remote-only dependency cache" >&2
      echo "failed" > "$status_file"
      touch "$WORKERS_FAILED_FILE"
      return 1
    fi
    echo "using remote wheel cache: $remote_url"
    harbor_write_effective_wheel_source "$remote_url"
    echo "remote" > "$status_file"
    harbor_mark_workers_ready
    return $?
  fi

  echo "preparing" > "$status_file"
  echo "local cache missing; downloading dependency cache..."
  local prepare_opencode_cache=0 prepare_pi_cache=0
  if harbor_agent_is_opencode; then
    prepare_opencode_cache=1
  elif harbor_agent_is_pi; then
    prepare_pi_cache=1
  fi
  if (cd "$SCRIPT_DIR" && WHEEL_DIR="$LOCAL_WHEEL_DIR" CACHE_SCHEMA=3 CLAUDE_CODE_VERSION="$CLAUDE_CODE_VERSION" CLAUDE_CODE_TGZ_BASENAME="$CLAUDE_CODE_TGZ_BASENAME" PREPARE_OPENCODE_CACHE="$prepare_opencode_cache" OPENCODE_VERSION="$OPENCODE_VERSION" OPENCODE_TGZ_BASENAME="$OPENCODE_TGZ_BASENAME" OPENCODE_LINUX_X64_TGZ_BASENAME="$OPENCODE_LINUX_X64_TGZ_BASENAME" PREPARE_PI_CACHE="$prepare_pi_cache" PI_VERSION="$PI_VERSION" PI_TGZ_BASENAME="$PI_TGZ_BASENAME" PI_NODE_RUNTIME_BASENAME="$PI_NODE_RUNTIME_BASENAME" PI_RUNTIME_BASENAME="$PI_RUNTIME_BASENAME" ./prepare_local_deps.sh 2>&1 | tee -a "$LOCAL_DEPS_LOG_FILE"); then
    harbor_build_verifier_runtime_bundle || {
      echo "failed" > "$status_file"
      touch "$WORKERS_FAILED_FILE"
      return 1
    }
    harbor_ensure_local_wheels_server
    harbor_write_effective_wheel_source "$HARBOR_LOCAL_WHEEL_SERVER_URL"
    harbor_prewarm_s3_upload_cache || {
      echo "failed" > "$status_file"
      touch "$WORKERS_FAILED_FILE"
      return 1
    }
    echo "done" > "$status_file"
    harbor_mark_workers_ready
    return $?
  fi

  echo "failed" > "$status_file"
  touch "$WORKERS_FAILED_FILE"
  return 1
}

harbor_prepare_agent_runtime() {
  if harbor_agent_is_oracle \
    || [[ "$ROLLOUT" == "1" && "$RL_AGENT" == "oracle" ]]; then
    mkdir -p "$RUNTIME_DIR"
    rm -f "$WORKERS_FAILED_FILE" "$HARBOR_RUNNER_PREPARE_STATUS_FILE"
    if harbor_prepare_verifier_runtime_bundle && harbor_validate_runner_cli; then
      touch "$WORKERS_READY_FILE"
      return 0
    fi
    touch "$WORKERS_FAILED_FILE"
    return 1
  fi

  if [[ "$HARBOR_ENVIRONMENT_TYPE" == "e2b" || "$HARBOR_ENVIRONMENT_TYPE" == "qz" ]]; then
    mkdir -p "$RUNTIME_DIR"
    rm -f "$WORKERS_FAILED_FILE" "$HARBOR_RUNNER_PREPARE_STATUS_FILE"
    if harbor_validate_runner_cli; then
      touch "$WORKERS_READY_FILE"
      return 0
    fi
    touch "$WORKERS_FAILED_FILE"
    return 1
  fi

  if harbor_agent_is_opencode; then
    if ! harbor_prepare_or_select_wheels; then
      echo "failed to prepare local dependency cache" >&2
      touch "$WORKERS_FAILED_FILE"
      return 1
    fi
    return 0
  fi

  if ! harbor_prepare_or_select_wheels; then
    echo "failed to prepare local dependency cache" >&2
    touch "$WORKERS_FAILED_FILE"
    return 1
  fi
}

harbor_validate_runner_cli() {
  python3 "$SCRIPT_DIR/harbor_prepare_runner_cli.py"
}

harbor_runner_cli_ready() {
  if [[ "$HARBOR_RUNNER_PREPARE" != "1" ]]; then
    [[ -x "$HARBOR_OPIK_BIN" && -x "$HARBOR_CLI_BIN" ]]
    return
  fi
  [[ -x "$HARBOR_OPIK_BIN" ]] \
    && [[ -x "$HARBOR_CLI_BIN" ]] \
    && [[ -x "$HARBOR_OPIK_PYTHON" ]] \
    && [[ "$(cat "$HARBOR_RUNNER_PREPARE_STATUS_FILE" 2>/dev/null || true)" == "done" ]]
}

harbor_mark_workers_ready() {
  if harbor_validate_runner_cli; then
    touch "$WORKERS_READY_FILE"
    return 0
  fi
  return 1
}
