#!/usr/bin/env bash
set -euo pipefail

# Fleet owns only Harbor integration glue. Builder, prompts, and gate behavior
# come from the sibling sii-fusion-router checkout.
MODEL_FUSION_DIR="${MODEL_FUSION_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"
FUSION_ROUTER_DIR="${FUSION_ROUTER_DIR:-$(cd "$REPO_ROOT/.." && pwd)/sii-fusion-router}"

TB_FUSION_ROUND_ROUTER_DIR="${TB_FUSION_ROUND_ROUTER_DIR:-${FUSION_ROUTER_DIR}/src/sii_fusion_router/frontends/claude_code}"
TB_FUSION_ROUND_ROUTER_MOUNT_PATH="${TB_FUSION_ROUND_ROUTER_MOUNT_PATH:-/opt/tb-fusion-round}"
TB_FUSION_ROUND_GATE="${TB_FUSION_ROUND_GATE:-0}"
TB_FUSION_ROUND_GATE_PATH="${TB_FUSION_ROUND_GATE_PATH:-${TB_FUSION_ROUND_ROUTER_MOUNT_PATH}/subagent_barrier_gate.py}"
TB_FUSION_ROUND_GATE_MODE="${TB_FUSION_ROUND_GATE_MODE:-mid-turn-fusion}"
TB_FUSION_TASK_BUILDER="${TB_FUSION_TASK_BUILDER:-${TB_FUSION_ROUND_ROUTER_DIR}/task_subagent_prompt.py}"
TB_FUSION_TASK_FILE_SOURCE="${TB_FUSION_TASK_FILE_SOURCE:-}"
TB_FUSION_TASK_FILE="${TB_FUSION_TASK_FILE:-/opt/tb-fusion-task/task.md}"
TB_FUSION_MAX_FUSIONS_PER_TASK="${TB_FUSION_MAX_FUSIONS_PER_TASK:-1}"
TB_FUSION_PANEL_CALL_BUDGET="${TB_FUSION_PANEL_CALL_BUDGET:-}"
SPAN_FORCE_MODE="${SPAN_FORCE_MODE:-mid-turn-fusion}"
SPAN_FORCE_FUSION="${SPAN_FORCE_FUSION:-1}"
SPAN_GATE_STATE_PATH="${SPAN_GATE_STATE_PATH:-/logs/agent/.gate-state.json}"
SPAN_MID_TURN_ARTIFACT_ROOT="${SPAN_MID_TURN_ARTIFACT_ROOT:-/logs/agent/span-mid-turn-artifacts}"
SPAN_HOOK_REASON_MAX_BYTES="${SPAN_HOOK_REASON_MAX_BYTES:-7000}"
SPAN_PANEL_MODELS="${SPAN_PANEL_MODELS:-$MODEL,$MODEL,$MODEL}"
TB_CLAUDE_CODE_AGENTS_JSON="${TB_CLAUDE_CODE_AGENTS_JSON:-}"

export MODEL_FUSION_DIR
export FUSION_ROUTER_DIR
export TB_FUSION_ROUND_ROUTER_DIR TB_FUSION_ROUND_ROUTER_MOUNT_PATH TB_FUSION_ROUND_GATE TB_FUSION_ROUND_GATE_PATH TB_FUSION_ROUND_GATE_MODE TB_FUSION_TASK_BUILDER TB_FUSION_TASK_FILE_SOURCE TB_FUSION_TASK_FILE
export TB_FUSION_MAX_FUSIONS_PER_TASK TB_FUSION_PANEL_CALL_BUDGET SPAN_FORCE_MODE SPAN_FORCE_FUSION SPAN_GATE_STATE_PATH SPAN_MID_TURN_ARTIFACT_ROOT SPAN_HOOK_REASON_MAX_BYTES SPAN_PANEL_MODELS TB_CLAUDE_CODE_AGENTS_JSON
