#!/usr/bin/env bash
set -euo pipefail

# Fleet owns only Harbor integration glue. Builder, prompts, and gate behavior
# come from the sibling sii-fusion-router checkout.
MODEL_FUSION_DIR="${MODEL_FUSION_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"
FUSION_ROUTER_DIR="${FUSION_ROUTER_DIR:-$(cd "$REPO_ROOT/.." && pwd)/sii-fusion-router}"

HARBOR_FUSION_ROUND_ROUTER_DIR="${HARBOR_FUSION_ROUND_ROUTER_DIR:-${FUSION_ROUTER_DIR}/src/sii_fusion_router/frontends/claude_code}"
HARBOR_FUSION_ROUND_ROUTER_MOUNT_PATH="${HARBOR_FUSION_ROUND_ROUTER_MOUNT_PATH:-/opt/tb-fusion-round}"
HARBOR_FUSION_ROUND_GATE="${HARBOR_FUSION_ROUND_GATE:-0}"
HARBOR_FUSION_ROUND_GATE_PATH="${HARBOR_FUSION_ROUND_GATE_PATH:-${HARBOR_FUSION_ROUND_ROUTER_MOUNT_PATH}/subagent_barrier_gate.py}"
HARBOR_FUSION_ROUND_GATE_MODE="${HARBOR_FUSION_ROUND_GATE_MODE:-mid-turn-fusion}"
HARBOR_FUSION_TASK_BUILDER="${HARBOR_FUSION_TASK_BUILDER:-${HARBOR_FUSION_ROUND_ROUTER_DIR}/task_subagent_prompt.py}"
HARBOR_FUSION_TASK_FILE_SOURCE="${HARBOR_FUSION_TASK_FILE_SOURCE:-}"
HARBOR_FUSION_TASK_FILE="${HARBOR_FUSION_TASK_FILE:-/opt/tb-fusion-task/task.md}"
HARBOR_FUSION_MAX_FUSIONS_PER_TASK="${HARBOR_FUSION_MAX_FUSIONS_PER_TASK:-1}"
HARBOR_FUSION_PANEL_CALL_BUDGET="${HARBOR_FUSION_PANEL_CALL_BUDGET:-}"
SPAN_FORCE_MODE="${SPAN_FORCE_MODE:-mid-turn-fusion}"
SPAN_FORCE_FUSION="${SPAN_FORCE_FUSION:-1}"
SPAN_GATE_STATE_PATH="${SPAN_GATE_STATE_PATH:-/logs/agent/.gate-state.json}"
SPAN_MID_TURN_ARTIFACT_ROOT="${SPAN_MID_TURN_ARTIFACT_ROOT:-/logs/agent/span-mid-turn-artifacts}"
SPAN_HOOK_REASON_MAX_BYTES="${SPAN_HOOK_REASON_MAX_BYTES:-7000}"
SPAN_PANEL_MODELS="${SPAN_PANEL_MODELS:-$MODEL,$MODEL,$MODEL}"
HARBOR_CLAUDE_CODE_AGENTS_JSON="${HARBOR_CLAUDE_CODE_AGENTS_JSON:-}"

export MODEL_FUSION_DIR
export FUSION_ROUTER_DIR
export HARBOR_FUSION_ROUND_ROUTER_DIR HARBOR_FUSION_ROUND_ROUTER_MOUNT_PATH HARBOR_FUSION_ROUND_GATE HARBOR_FUSION_ROUND_GATE_PATH HARBOR_FUSION_ROUND_GATE_MODE HARBOR_FUSION_TASK_BUILDER HARBOR_FUSION_TASK_FILE_SOURCE HARBOR_FUSION_TASK_FILE
export HARBOR_FUSION_MAX_FUSIONS_PER_TASK HARBOR_FUSION_PANEL_CALL_BUDGET SPAN_FORCE_MODE SPAN_FORCE_FUSION SPAN_GATE_STATE_PATH SPAN_MID_TURN_ARTIFACT_ROOT SPAN_HOOK_REASON_MAX_BYTES SPAN_PANEL_MODELS HARBOR_CLAUDE_CODE_AGENTS_JSON
