#!/usr/bin/env bash
set -euo pipefail

OPENROUTER_DIR="${OPENROUTER_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"
REPO_ROOT="${REPO_ROOT:-$(cd "$OPENROUTER_DIR/../../../../../.." && pwd)}"
FUSION_ROUTER_DIR="${FUSION_ROUTER_DIR:-$(cd "$REPO_ROOT/.." && pwd)/sii-fusion-router}"
OPENROUTER_WHEEL_MOUNT_PATH="${OPENROUTER_WHEEL_MOUNT_PATH:-/opt/sii-fusion-router/router.whl}"
OPENROUTER_CONFIG_MOUNT_PATH="${OPENROUTER_CONFIG_MOUNT_PATH:-/opt/sii-fusion-router/router-config.json}"
OPENROUTER_ARTIFACT_ROOT="${OPENROUTER_ARTIFACT_ROOT:-/logs/agent/router}"
OPENROUTER_SUMMARY_PATH="${OPENROUTER_SUMMARY_PATH:-/logs/agent/router-run-summary.json}"

export OPENROUTER_DIR REPO_ROOT FUSION_ROUTER_DIR
export OPENROUTER_WHEEL OPENROUTER_VERSION OPENROUTER_CONFIG
export OPENROUTER_WHEEL_MOUNT_PATH OPENROUTER_CONFIG_MOUNT_PATH
export OPENROUTER_ARTIFACT_ROOT OPENROUTER_SUMMARY_PATH
