#!/usr/bin/env bash
set -euo pipefail

# Rollout configuration handoff and shared RL defaults.
# Sourced by ../env.sh; SCRIPT_DIR remains the Harbor directory.

# ── RL rollout mode ──────────────────────────────────────────────────────────
# Keep RL-specific implementation outside common/Harbor; Harbor only exposes the
# start.sh entry point and shared benchmark/runtime configuration.
RL_UTILS_DIR="${RL_UTILS_DIR:-$REPO_ROOT/Agents/utils/rl}"
RL_ENV_FILE="${RL_ENV_FILE:-$RL_UTILS_DIR/RL-env.sh}"
if [[ "$ROLLOUT" == "1" && -f "$RL_ENV_FILE" ]]; then
  RL_MODEL_NAME="${RL_MODEL_NAME:-$_HARBOR_EFFECTIVE_MODEL}"
  RL_API_BASE="${RL_API_BASE:-${HARBOR_ANTHROPIC_BASE_URL:+${HARBOR_ANTHROPIC_BASE_URL}/v1}}"
  RL_API_KEY="${RL_API_KEY:-$HARBOR_ANTHROPIC_AUTH_TOKEN}"
  # shellcheck source=/dev/null
  . "$RL_ENV_FILE"
fi
RL_HOST="${RL_HOST:-0.0.0.0}"
RL_PORT="${RL_PORT:-19001}"
RL_DATASET_NAME="${RL_DATASET_NAME:-$DATASET_NAME}"
if [[ "$RL_DATASET_NAME" == "auto" ]]; then
  RL_DATASET_NAME="seta"
fi
RL_DATASET_ROOT="${RL_DATASET_ROOT:-$DATASET_PATH}"
RL_DATASET_ROOTS="${RL_DATASET_ROOTS:-}"
RL_TRIALS_DIR="${RL_TRIALS_DIR:-${OUTPUT_ROOT}/rl-remote-trials}"
RL_MAX_CONCURRENT="${RL_MAX_CONCURRENT:-16}"
RL_AGENT="${RL_AGENT:-claude-code}"
RL_MODEL_NAME="${RL_MODEL_NAME:-$_HARBOR_EFFECTIVE_MODEL}"
RL_MODEL_PREFIX="${RL_MODEL_PREFIX:-hosted_vllm}"
if [[ -z "${RL_API_BASE:-}" && -n "${BASE_URL:-}" ]]; then
  RL_API_BASE="${BASE_URL%/}/v1"
fi
RL_API_BASE="${RL_API_BASE:-}"
RL_API_KEY="${RL_API_KEY:-$API_KEY}"
RL_API_KEY_MODE="${RL_API_KEY_MODE:-static}"
MODEL_REQUEST_CONFIG_JSON="${MODEL_REQUEST_CONFIG_JSON:-}"
RL_DISABLED_TASK_IDS="${RL_DISABLED_TASK_IDS:-}"
RL_ENVIRONMENT_TYPE="${RL_ENVIRONMENT_TYPE:-docker}"
RL_E2B_SANDBOX_TIMEOUT_SEC="${RL_E2B_SANDBOX_TIMEOUT_SEC:-}"
RL_E2B_PREBUILT_TEMPLATE="${RL_E2B_PREBUILT_TEMPLATE:-}"
HARBOR_ENVIRONMENT_TYPE="${HARBOR_ENVIRONMENT_TYPE:-$RL_ENVIRONMENT_TYPE}"
HARBOR_E2B_SANDBOX_TIMEOUT_SEC="${HARBOR_E2B_SANDBOX_TIMEOUT_SEC:-$RL_E2B_SANDBOX_TIMEOUT_SEC}"
HARBOR_E2B_PREBUILT_TEMPLATE="${HARBOR_E2B_PREBUILT_TEMPLATE:-${RL_E2B_PREBUILT_TEMPLATE:-${E2B_TEMPLATE:-}}}"
HARBOR_E2B_PREBUILT_ENVIRONMENT_SPEC="${HARBOR_E2B_PREBUILT_ENVIRONMENT_SPEC:-e2b_prebuilt:PrebuiltE2BEnvironment}"
RL_FORCE_BUILD="${RL_FORCE_BUILD:-$HARBOR_FORCE_BUILD}"
RL_TRACE_LOG="${RL_TRACE_LOG:-${RUNTIME_DIR}/rl-rollout-requests.jsonl}"
RL_SERVER_LOG="${RL_SERVER_LOG:-${RUNTIME_DIR}/rl-rollout-server.log}"
RL_SERVER_PID_FILE="${RL_SERVER_PID_FILE:-${RUNTIME_DIR}/rl-rollout-server.pid}"
RL_QUEUE_DIR="${RL_QUEUE_DIR:-${RUNTIME_DIR}/rl-queue}"
RL_ACTIVE_DIR="${RL_ACTIVE_DIR:-${RL_QUEUE_DIR}/active}"
RL_JOB_QUEUE_ROOT="${RL_JOB_QUEUE_ROOT:-${RL_QUEUE_DIR}/jobs}"
RL_JOB_RUNTIME_ROOT="${RL_JOB_RUNTIME_ROOT:-${RUNTIME_DIR}/rl-jobs}"
RL_DYNAMIC_JOB_ZELLIJ="${RL_DYNAMIC_JOB_ZELLIJ:-1}"
RL_JOB_ZELLIJ_START_TIMEOUT="${RL_JOB_ZELLIJ_START_TIMEOUT:-120}"
RL_JOB_ZELLIJ_LOCK_TIMEOUT="${RL_JOB_ZELLIJ_LOCK_TIMEOUT:-30}"
RL_JOB_ZELLIJ_READY_TIMEOUT="${RL_JOB_ZELLIJ_READY_TIMEOUT:-90}"
RL_WORKERS="${RL_WORKERS:-${RL_MAX_CONCURRENT:-$TOTAL_WORKERS}}"
RL_REQUEST_TIMEOUT="${RL_REQUEST_TIMEOUT:-3600}"
RL_KEEP_TRIALS_PER_WORKER="${RL_KEEP_TRIALS_PER_WORKER:-20}"
RL_MODEL_INFO="${RL_MODEL_INFO:-$HARBOR_MODEL_INFO}"
RL_MAX_NEW_TOKENS="${RL_MAX_NEW_TOKENS:-}"
RL_CLAUDE_CODE_MAX_OUTPUT_TOKENS="${RL_CLAUDE_CODE_MAX_OUTPUT_TOKENS:-}"
RL_MAX_TURNS="${RL_MAX_TURNS:-32}"
RL_AGENT_TIMEOUT_MULTIPLIER="${RL_AGENT_TIMEOUT_MULTIPLIER:-$HARBOR_AGENT_TIMEOUT_MULTIPLIER}"
RL_LLM_TIMEOUT="${RL_LLM_TIMEOUT:-900}"
RL_LLM_MAX_RETRIES="${RL_LLM_MAX_RETRIES:-0}"
RL_TEMPERATURE="${RL_TEMPERATURE:-1.0}"
RL_TOP_P="${RL_TOP_P:-1.0}"
RL_TOP_K="${RL_TOP_K:--1}"
RL_MIN_P="${RL_MIN_P:-0.0}"
RL_COLLECT_ROLLOUT_DETAILS="${RL_COLLECT_ROLLOUT_DETAILS:-true}"
RL_ENABLE_SUMMARIZE="${RL_ENABLE_SUMMARIZE:-false}"
