#!/usr/bin/env bash
set -euo pipefail

# Provider connection, upload, package-source, and preflight defaults.
# Sourced by ../env.sh; SCRIPT_DIR remains the Harbor directory.

# OpenSandbox must always resolve to an explicit YiCloud environment. Keep the
# values empty in the public template; harboropik.sh fails before any API call
# when neither an immutable ID nor an exact environment name is configured.
YICLOUD_SANDBOX_ENVIRONMENT_ID="${YICLOUD_SANDBOX_ENVIRONMENT_ID:-}"
YICLOUD_SANDBOX_ENVIRONMENT_NAME="${YICLOUD_SANDBOX_ENVIRONMENT_NAME:-}"
YICLOUD_SANDBOX_READY_TIMEOUT_SEC="${YICLOUD_SANDBOX_READY_TIMEOUT_SEC:-300}"
YICLOUD_SANDBOX_STATUS_LOG_INTERVAL_SEC="${YICLOUD_SANDBOX_STATUS_LOG_INTERVAL_SEC:-30}"
YICLOUD_SANDBOX_RETAIN_ON_START_FAILURE="${YICLOUD_SANDBOX_RETAIN_ON_START_FAILURE:-0}"
YICLOUD_SANDBOX_RETAIN_AFTER_TRIAL="${YICLOUD_SANDBOX_RETAIN_AFTER_TRIAL:-0}"
YICLOUD_SANDBOX_PROXY_ORIGIN="${YICLOUD_SANDBOX_PROXY_ORIGIN:-}"
YICLOUD_SANDBOX_FAST_UPLOAD_ORIGIN="${YICLOUD_SANDBOX_FAST_UPLOAD_ORIGIN-https://sandbox.yicloud.com.cn}"
YICLOUD_SANDBOX_UPLOAD_TIMEOUT_SEC="${YICLOUD_SANDBOX_UPLOAD_TIMEOUT_SEC:-1800}"
YICLOUD_SANDBOX_S3_PROFILE="${YICLOUD_SANDBOX_S3_PROFILE:-}"
harbor_resolve_opensandbox_s3_profile "$REPO_ROOT"
YICLOUD_SANDBOX_UPLOAD_BACKEND="${YICLOUD_SANDBOX_UPLOAD_BACKEND:-http}"
YICLOUD_SANDBOX_S3_CONFIG="${YICLOUD_SANDBOX_S3_CONFIG:-}"
YICLOUD_SANDBOX_S3_BUCKET="${YICLOUD_SANDBOX_S3_BUCKET:-}"
YICLOUD_SANDBOX_S3_READ_ORIGIN="${YICLOUD_SANDBOX_S3_READ_ORIGIN:-}"
YICLOUD_SANDBOX_S3_PREFIX="${YICLOUD_SANDBOX_S3_PREFIX:-agent-fleet-upload/v1}"
YICLOUD_SANDBOX_S3_CACHE_ROOT="${YICLOUD_SANDBOX_S3_CACHE_ROOT:-${RUNTIME_DIR}/s3-upload-cache}"
YICLOUD_SANDBOX_S3_LOCK_ROOT="${YICLOUD_SANDBOX_S3_LOCK_ROOT:-${RUNTIME_DIR}/s3-upload-locks}"
YICLOUD_SANDBOX_S3_DOWNLOAD_TIMEOUT_SEC="${YICLOUD_SANDBOX_S3_DOWNLOAD_TIMEOUT_SEC:-1800}"
YICLOUD_SANDBOX_S3_DIRECTORY_COMPRESSION="${YICLOUD_SANDBOX_S3_DIRECTORY_COMPRESSION:-auto}"
YICLOUD_SANDBOX_S3CMD="${YICLOUD_SANDBOX_S3CMD:-${HARBOR_RUNNER_DIR}/bin/s3cmd}"
YICLOUD_SANDBOX_CPU="${YICLOUD_SANDBOX_CPU:-2}"
YICLOUD_SANDBOX_MEMORY="${YICLOUD_SANDBOX_MEMORY:-8Gi}"
YICLOUD_SANDBOX_LIFECYCLE_MINUTES="${YICLOUD_SANDBOX_LIFECYCLE_MINUTES:-120}"
export YICLOUD_SANDBOX_ENVIRONMENT_ID YICLOUD_SANDBOX_ENVIRONMENT_NAME
export YICLOUD_SANDBOX_READY_TIMEOUT_SEC
export YICLOUD_SANDBOX_STATUS_LOG_INTERVAL_SEC
export YICLOUD_SANDBOX_RETAIN_ON_START_FAILURE
export YICLOUD_SANDBOX_RETAIN_AFTER_TRIAL
export YICLOUD_SANDBOX_PROXY_ORIGIN
export YICLOUD_SANDBOX_FAST_UPLOAD_ORIGIN
export YICLOUD_SANDBOX_UPLOAD_TIMEOUT_SEC YICLOUD_SANDBOX_UPLOAD_BACKEND
export YICLOUD_SANDBOX_S3_PROFILE
export YICLOUD_SANDBOX_S3_CONFIG YICLOUD_SANDBOX_S3_BUCKET
export YICLOUD_SANDBOX_S3_READ_ORIGIN
export YICLOUD_SANDBOX_S3_PREFIX YICLOUD_SANDBOX_S3_CACHE_ROOT
export YICLOUD_SANDBOX_S3_LOCK_ROOT
export YICLOUD_SANDBOX_S3_DOWNLOAD_TIMEOUT_SEC
export YICLOUD_SANDBOX_S3_DIRECTORY_COMPRESSION
export YICLOUD_SANDBOX_S3CMD
export YICLOUD_SANDBOX_CPU YICLOUD_SANDBOX_MEMORY
export YICLOUD_SANDBOX_LIFECYCLE_MINUTES

# qz (SII Inspire) E2B-compatible sandbox connection. Values usually come from
# config.local.env; re-export here so shell-provided values survive into
# worker panes. The qz adapter maps SBX_*/QZ_SANDBOX_* onto the official e2b
# SDK. Those qz values override ambient cloud-E2B connection and transport
# settings inside a qz process; E2B_API_KEY remains a fallback only when it
# contains an sbx_-prefixed qz key.
QZ_SANDBOX_API_KEY="${QZ_SANDBOX_API_KEY:-}"
QZ_SANDBOX_API_URL="${QZ_SANDBOX_API_URL:-}"
QZ_SANDBOX_TEMPLATE="${QZ_SANDBOX_TEMPLATE:-}"
QZ_SANDBOX_TEMPLATE_MAP="${QZ_SANDBOX_TEMPLATE_MAP:-}"
QZ_SANDBOX_TIMEOUT_SEC="${QZ_SANDBOX_TIMEOUT_SEC:-}"
SBX_API_KEY="${SBX_API_KEY:-}"
SBX_API_URL="${SBX_API_URL:-}"
export QZ_SANDBOX_API_KEY QZ_SANDBOX_API_URL QZ_SANDBOX_TEMPLATE
export QZ_SANDBOX_TEMPLATE_MAP
export QZ_SANDBOX_TIMEOUT_SEC SBX_API_KEY SBX_API_URL

UV_INDEX_URL="${UV_INDEX_URL:-$PIP_INDEX_URL}"
UV_DEFAULT_INDEX="${UV_DEFAULT_INDEX:-$UV_INDEX_URL}"

HARBOR_PIP_DEFAULT_TIMEOUT="${HARBOR_PIP_DEFAULT_TIMEOUT:-120}"
HARBOR_PIP_RETRIES="${HARBOR_PIP_RETRIES:-10}"
HARBOR_SKIP_DOCKERHUB_PREFLIGHT="${HARBOR_SKIP_DOCKERHUB_PREFLIGHT:-0}"
HARBOR_DOCKERHUB_CHECK_TIMEOUT="${HARBOR_DOCKERHUB_CHECK_TIMEOUT:-8}"
HARBOR_DOCKERHUB_PREFLIGHT_STRICT="${HARBOR_DOCKERHUB_PREFLIGHT_STRICT:-0}"
SMITH_GENERATE_IF_MISSING="${SMITH_GENERATE_IF_MISSING:-1}"
SMITH_ADAPTER_DIR="${SMITH_ADAPTER_DIR:-$HARBOR_ROOT/adapters/swesmith}"
FIX_GIT_IMAGE_NAME="${FIX_GIT_IMAGE_NAME:-xiangyangli/fix-git:20260204}"
FIX_GIT_WARM_LABEL="${FIX_GIT_WARM_LABEL:-io.codex.prewarmed}"
